%% Figure 1-3

% These figures are not generated by Matlab

%% Figure 4

% Left pane:
showAquiferModel;

% Right pane:
showDensityVariation;

%% Figure 5

runStandardModel('data/residualExample1Data', @plotResidualFigs , ...
                 'A'             , [0 2]                        , ...
                 'residual'      , [false true]                 , ...
                 'relperm_types' , {'sharp interface'}          , ...
                 'dis_types'     , {'none'});
