function tab_comp = make_purecomponent_table_H2(varargin)
% MAKE_PURECOMPONENT_TABLE_H2 Generate tables for H2O and H2 pure fluid properties
%
% SYNOPSIS:
%   tab_comp = MAKE_PURECOMPONENT_TABLE_H2('min_temp', 0, 'max_temp', 100,
%                                      'n_temp', 3, 'min_press', 1e5,
%                                      'max_press', 1e5, 'n_press', 2,
%                                      'comp_name', 'H2O',
%                                      'display_output', false,
%                                      'output_dir', dir)
%
% DESCRIPTION:
%   This function generates a table for the fluid properties of a given
%   component (e.g., H2 or H2O)  at std conditions (see below).
%
% REQUIRED PARAMETERS:
%   'min_temp'    - Minimum temperature in Celsius (default: 0°C)
%   'max_temp'    - Maximum temperature in Celsius (default: 0°C)
%   'n_temp'      - Number of temperature points (default: 3)
%   'min_press'   - Minimum pressure in Pascals (default: 1e5 Pa)
%   'max_press'   - Maximum pressure in Pascals (default: 1e5 Pa)
%   'n_press'     - Number of pressure points (default: 2)
%   'comp_name'   - Name of the component (default: 'H2O')
%
% OPTIONAL PARAMETERS:
%   'display_output'  - If true, displays the generated table. Default: false
%   'output_dir'      - Directory where the output file is saved. Default: current directory.
%   'output_file'     - File name for the generated table.
%
% EXAMPLE USAGE:
%   tab_comp = MAKE_PURECOMPONENT_TABLE_H2('min_temp', 0, 'max_temp', 0, ...
%                                       'n_temp', 3, 'min_press', 1e5, ...
%                                       'max_press', 1e5, 'n_press', 2, ...
%                                       'comp_name', 'H2O', ...
%                                       'output_dir', '/path/to/output', ...
%                                       'output_file', 'water');
%
% COPYRIGHT:
%   Copyright 2009-2025 SINTEF Digital, Mathematics & Cybernetics.
%   This file is part of The MATLAB Reservoir Simulation Toolbox (MRST).
%
%   MRST is free software: you can redistribute it and/or modify
%   it under the terms of the GNU General Public License as published by
%   the Free Software Foundation, either version 3 of the License, or
%   (at your option) any later version.
%
%   MRST is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
%   GNU General Public License for more details.
%
%   You should have received a copy of the GNU General Public License
%   along with MRST. If not, see <http://www.gnu.org/licenses/>.

% Input parameters
opt = struct(...
    'min_temp', 0, ...           % Default: 0°C
    'max_temp', 100, ...         % Default: 100°C
    'n_temp', 3, ...             % Default: 3 points
    'min_press', 1*1e5, ...      % Default: 1 atm (1e5 Pa)
    'max_press', 1*1e5, ...      % Default: 1 atm (1e5 Pa)
    'n_press', 2, ...            % Default: 2 points
    'comp_name', 'H2O', ...      % Default: 'H2O'
    'display_output', false, ... % Default: false (auto-generated)
    'output_dir', '.', ...       % Default: current directory
    'file_name', 'component_table.csv' ...  % Default: 'component_table.csv'
    );

% Merge user inputs with the defaults
opt = merge_options(opt, varargin{:});

% Rest of the function remains the same...
minTemp = opt.min_temp;
maxTemp = opt.max_temp;
nTemp = opt.n_temp;

if nTemp == 1
    delta_temperature = 0;
else
    delta_temperature = (maxTemp - minTemp) / (nTemp - 1);
end

minPress = opt.min_press;
maxPress = opt.max_press;
nPress = opt.n_press;

fprintf('Component: %s\n', opt.comp_name);
fprintf('Temperature at std conditions: %.1f to %.1f °C (%d points)\n', minTemp, maxTemp, nTemp);
fprintf('Pressure at std conditions: %.1f', minPress);

delta_pressure = nPress;
compName = opt.comp_name;

% Set output filename
fileName = sprintf('%s_pure_values_%.1f_to_%.1f_bar_%.1f_to_%.1f_C.csv', ...
        lower(compName), minPress, maxPress, minTemp, maxTemp);

% Ensure the output directory exists
if ~exist(opt.output_dir, 'dir')
    mkdir(opt.output_dir);
end

% Full path to the output file
filePath = fullfile(opt.output_dir, fileName);

% Open the output file
outFile = fopen(filePath, 'w');
if outFile == -1
    error('Could not open the file: %s', filePath);
end

fprintf(outFile, '# This autogenerated file contains thermodynamical properties of %s.\n', compName);
fprintf(outFile, '# The data has been obtained by querying the NIST Chemistry WebBook https://doi.org/10.18434/T4D303.\n#\n');
fprintf(outFile, '# Concerning temperature and pressure ranges, the following parameters have been used:\n');
fprintf(outFile, '# min temperature = %.1f, max temperature = %.1f, #temperature sampling points = %d\n', ...
    minTemp, maxTemp, nTemp);
fprintf(outFile, '# min pressure = %.1f, max pressure = %.1f, #pressure sampling points = %d\n#\n', ...
    minPress, maxPress, nPress);
fprintf(outFile, '# temperature [°C],     pressure [Pa],   density [kg/m3],  viscosity [Pa.s],   enthalpy [J/kg]\n');

% Get data from NIST
for i = 1:nTemp
    temperature = minTemp + (i-1) * delta_temperature;
    query = struct(...
        'Action', 'Data', ...
        'Wide', 'on', ...
        'ID', 'C7732185', ... % H2O
        'Type', 'IsoTherm', ...
        'Digits', '12', ...
        'PLow', num2str(minPress), ...
        'PHigh', num2str(maxPress), ...
        'PInc', num2str(delta_pressure), ...
        'T', num2str(temperature), ...
        'RefState', 'DEF', ...
        'TUnit', 'C', ...
        'PUnit', 'Pa', ...
        'DUnit', 'kg/m3', ...
        'HUnit', 'kJ/kg', ...
        'WUnit', 'm/s', ...
        'VisUnit', 'uPas', ...
        'STUnit', 'N/m');
    
    if strcmpi(compName, 'H2')
        query.ID = 'C1333740'; % H2
    end
    
    queryStr = '';
    fields = fieldnames(query);
    for k = 1:length(fields)
        if k > 1
            queryStr = [queryStr '&'];
        end
        queryStr = [queryStr fields{k} '=' query.(fields{k})];
    end
    
    try
        response = webread(['https://webbook.nist.gov/cgi/fluid.cgi?' queryStr]);
        responseStr = char(response)';  % Convert uint8 to character array
        % Save the response as a temporary text file and read it
        tempFile = 'temp_data.txt';
        fid = fopen(tempFile, 'w');
        fprintf(fid, '%s', responseStr);
        fclose(fid);
        % Read the table
        data = readtable(tempFile, 'Delimiter', '\t', 'ReadVariableNames', true,'VariableNamingRule', 'preserve');
        % Delete the temporary file
        delete(tempFile);
        % Retrive the necessary data
        phase = data.Phase;
        uniquePhases = unique(phase);
        if numel(uniquePhases) > 1
            % Detect phase transitions
            phaseTransitionForward = [diff(phase) ~= 0; false];
            phaseTransitionBackward = [false; diff(phase) ~= 0];
            isNotPhaseTransition = ~(phaseTransitionForward | phaseTransitionBackward);
        else
            % If there's only one phase, no transitions exist
            phaseTransitionForward = false(size(phase));
            phaseTransitionBackward = false(size(phase));
            isNotPhaseTransition = true(size(phase));
        end


        pressure = data.("Pressure (Pa)")(isNotPhaseTransition);
        density = data.("Density (kg/m3)")(isNotPhaseTransition);
        viscosity = data.("Viscosity (uPa*s)")(isNotPhaseTransition) * 1e-6; % Convert to Pa.s
        enthalpy = data.("Enthalpy (kJ/kg)")(isNotPhaseTransition) * 1000;   % Convert to J/kg
        
        for j = 1:length(pressure)
            fprintf(outFile, ' %.11e, %.11e, %.11e, %.11e, %.11e\n', ...
                temperature, pressure(j), density(j), viscosity(j), enthalpy(j));
        end
    catch ME
        warning('Failed to retrieve data for T=%.1f°C: %s', temperature, ME.message);
    end
end

fclose(outFile);
fprintf('A file %s has been generated in %s.\n', fileName, opt.output_dir);
try
    if opt.display_output
        tab_comp = readtable(filePath,  'VariableNamingRule', 'preserve');
        display(tab_comp);
        disp('Table read successfully:');
    end
catch ME
    disp('Error occurred while reading the table:');
    disp(ME.message);
    tab_comp = []; % Return empty if reading fails
end
