% Run this file to load the MRST modules required for the examples and install the necessary paths.

mrstModule add ad-core ad-blackoil compositional ad-props mrst-gui mpsaw mpfa libgeometry vemmech

addpath('.');

dirnames = { 'assembly'      , ...
             'examples'      , ...
             'experimental'  , ...
             'models'        , ...
             'statefunctions', ...
             'tests'         , ...
             'utils'};

for ind = 1 : numel(dirnames)
    dirname = dirnames{ind};
    addpath(genpath(dirname));
end
