test_solver: test_solver.cpp FlexibleSolver.hpp GetQuasiImpesWeights.hpp PressureSolverPolicy.hpp PressureTransferPolicyTranspose.hpp OwningTwolevelPreconditioner.hpp PressureTransferPolicy.hpp makePreconditioner.hpp 
	g++ -g -o test_solver test_solver.cpp -I/Users/atgeirr/duneinstallhack/include -std=c++14 -L/Users/atgeirr/duneinstallhack/lib -lstdc++ -lm -ldunecommon
