function f = limitedToolbarFigure(varargin)
f = figure(varargin{:});
f.MenuBar = 'none';
f.ToolBar = 'figure';
f.DockControls = 'off';

cl = allchild(allchild(f));

% list which buttons to keep and not:
% keep  -  tooltipstring
l = {...
0, 'Show Plot Tools and Dock Figure',...
0, 'Hide Plot Tools',...
0, 'Insert Legend',...
0, 'Insert Colorbar',...
0, 'Link Plot',...
0, 'Brush/Select Data',...
0, 'Data Cursor',...
1, 'Rotate 3D',...
1, 'Pan',...
1, 'Zoom Out',...
1, 'Zoom In',...
0, 'Edit Plot',...
0, 'Print Figure',...
0, 'Save Figure',...
0, 'Open File',...
0, 'New Figure'};

l = l(2*find(cell2mat(l(1:2:end))));
set(cl, 'Visible', 'off');
set(cl, 'Separator', 'off');
for k = 1:numel(l)
    c = findall(cl,'ToolTipString', l{k});
    set(c, 'Visible', 'on');
end
end
    