function paper = paper_MRST_comg()
    paper = createPaperStruct('id', 'mrst-comg', ...
                              'name', 'Open source MATLAB implementation of consistent discretisations on complex grids', ...
                              'authors', 'K.-A. Lie, S. Krogstad, I. S. Ligaarden, J. R. Natvig, H. M. Nilsen, and B. Skaflestad', ...
                              'published', 'Computational Geosciences, , Vol. 16, No. 2, pp. 297-322', ...
                              'year', 2012, ...
                              'modules', {'mimetic', 'incomp', 'mpfa'}, ...
                              'url', 'http://link.springer.com/article/10.1007/s10596-011-9244-4', ...
                              'fileurl', 'http://folk.uio.no/kalie/papers/mrst-comg.pdf');
end