function paper = paper_MRSTAD()
    paper = createPaperStruct('id', 'mrst-ad', ...
                              'name', 'MRST-AD – an Open-Source Framework for Rapid Prototyping and Evaluation of Reservoir Simulation Problems', ...
                              'authors', 'S. Krogstad, K.-A. Lie, O. Møyner, H. M. Nilsen, X. Raynaud, and B. Skaflestad', ...
                              'published', 'Paper 173317-MS presented at the 2015 Reservoir simulation Symposium', ...
                              'year', 2015, ...
                              'modules', {'ad-core', 'ad-blackoil'}, ...
                              'url', 'https://www.onepetro.org/conference-paper/SPE-173317-MS', ...
                              'fileurl', 'http://folk.uio.no/kalie/papers/rss15-mrst.pdf');
end