function [problem, state] = equationsCO2( ...
        state0, state, model, dt, drivingForces, varargin)
% Assemble the linearized equations for the water-CO2 system.
%
% The non-wetting CO2 phase is represented internally by the oil phase of
% MRST's TwoPhaseOilWaterModel.
%
% This function is modified from a file in the MATLAB Reservoir Simulation
% Toolbox (MRST), see
%   mrst/modules/ad-eor/utils/equationsOilWaterPolymer.m
%
% We refer to that function for a complete commented version of the file.

%{
Partial copyright 2009-2021, SINTEF Digital, Mathematics & Cybernetics.
Partial copyright 2021-2026, NORCE Research AS, Computational Geosciences and
Modeling.

This file is part of the ad-micp module.

ad-micp is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

ad-micp is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this file. If not, see <http://www.gnu.org/licenses/>.
%}
    options = struct( ...
        'Verbose', mrstVerbose, ...
        'reverseMode', false, ...
        'resOnly', false, ...
        'iteration', -1);

    options = merge_options(options, varargin{:});

    fluid = model.fluid;
    grid = model.G;
    operators = model.operators;

    % Phase densities
    cellTemplate = ones(grid.cells.num, 1);

    waterDensity = ...
        fluid.rhoWS .* cellTemplate;

    co2Density = ...
        fluid.rhoOS .* cellTemplate;

    % Properties at the current timestep
    [pressure, waterSaturation, wellSol] = ...
        model.getProps( ...
        state, ...
        'pressure', ...
        'water', ...
        'wellSol');

    % Properties at the previous timestep
    [waterSaturation0, wellSol0] = ...
        model.getProps( ...
        state0, ...
        'water', ...
        'wellSol');

    [wellVariables, wellVariableNames, wellMap] = ...
        model.FacilityModel.getAllPrimaryVariables(wellSol);

    phasePrimaryVariables = { ...
        'pressure', ...
        'sW'};

    % Initialize independent variables
    if options.resOnly
        primaryVariables = phasePrimaryVariables;
    elseif options.reverseMode
        waterSaturation0 = ...
            initVariablesADI(waterSaturation0);

        primaryVariables = phasePrimaryVariables;
    else
        [pressure, waterSaturation, wellVariables{:}] = ...
            initVariablesADI( ...
            pressure, ...
            waterSaturation, ...
            wellVariables{:});

        primaryVariables = [ ...
            phasePrimaryVariables, ...
            wellVariableNames(:)'];
    end

    % The oil phase of the parent model represents CO2.
    co2Saturation = 1 - waterSaturation;
    co2Saturation0 = 1 - waterSaturation0;

    % Linear relative-permeability relationships
    waterRelativePermeability = waterSaturation;
    co2RelativePermeability = co2Saturation;

    transmissibility = operators.T;
    gravityGradient = model.getGravityGradient();

    [waterFlux, waterMobility] = ...
        getFluxAndPropsWater( ...
        model, ...
        pressure, ...
        waterRelativePermeability, ...
        transmissibility, ...
        gravityGradient);

    [co2Flux, co2Mobility] = ...
        getFluxAndPropsCO2( ...
        model, ...
        pressure, ...
        co2RelativePermeability, ...
        transmissibility, ...
        gravityGradient);

    if model.outputFluxes
        state = model.storeFluxes( ...
            state, waterFlux, co2Flux, []);
    end

    accumulationScale = operators.pv ./ dt;

    % Conservation of mass for water
    waterEquation = ...
        accumulationScale .* ...
        (waterSaturation - waterSaturation0) + ...
        operators.Div(waterFlux);

    % Conservation of mass for CO2. The equation name remains 'oil' for
    % compatibility with TwoPhaseOilWaterModel and the MRST well framework.
    co2Equation = ...
        accumulationScale .* ...
        (co2Saturation - co2Saturation0) + ...
        operators.Div(co2Flux);

    equations = { ...
        waterEquation, ...
        co2Equation};

    equationNames = { ...
        'water', ...
        'oil'};

    equationTypes = repmat({'cell'}, size(equations));

    phasePressures = { ...
        pressure, ...
        pressure};

    phaseSaturations = { ...
        waterSaturation, ...
        co2Saturation};

    phaseMobilities = { ...
        waterMobility, ...
        co2Mobility};

    phaseDensities = { ...
        waterDensity, ...
        co2Density};

    dissolvedGasRatios = {};
    components = {};

    [equations, state] = addBoundaryConditionsAndSources( ...
        model, ...
        equations, ...
        equationNames, ...
        equationTypes, ...
        state, ...
        phasePressures, ...
        phaseSaturations, ...
        phaseMobilities, ...
        phaseDensities, ...
        dissolvedGasRatios, ...
        components, ...
        drivingForces);

    [equations, equationNames, equationTypes, state.wellSol] = ...
        model.insertWellEquations( ...
        equations, ...
        equationNames, ...
        equationTypes, ...
        wellSol0, ...
        wellSol, ...
        wellVariables, ...
        wellMap, ...
        pressure, ...
        phaseMobilities, ...
        phaseDensities, ...
        dissolvedGasRatios, ...
        components, ...
        dt, ...
        options);

    problem = LinearizedProblem( ...
        equations, ...
        equationTypes, ...
        equationNames, ...
        primaryVariables, ...
        state, ...
        dt);
end
