function name = propFilename(P_range, T_range, P_num, T_num, fluid, prop)
% Standardized filename generator for a sampled table of a given property of
% a given fluid, with given sample parameters.
   name = [fluid, ...
           '_', ...
           num2str(P_range, '%d_'), ...
           num2str(T_range, '%d_'), ...
           num2str(P_num,   '%d_'), ...
           num2str(T_num,   '%d_'), ...
           prop, '.mat'];
end
