
names = {'autodiff', ...
         'thirdparty-modules', ...
         'multiscale', ...
         'visualization', ...
         'model-io', ...
         'solvers'};
names = cellfun(@(x) fullfile(ROOTDIR, '..', ['mrst-', x]), names, ...
                    'UniformOutput', false);

mrstPath('addroot', names{:});
mrstPath('add', 'co2lab', fullfile(ROOTDIR, '..', 'mrst-co2lab', 'co2lab'));

clear names