%% Copyright notice
%{
Copyright 2026, NORCE Research AS, Computational Geosciences and
Modeling.

This file is part of the ad-micp module.

ad-micp is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

ad-micp is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this file. If not, see <http://www.gnu.org/licenses/>.
%}

AD_MICP_TEST = true;

orig = pwd();
testsdir = fullfile(orig, "tests");

relative_tol = 1e-5;
absolute_tol = 1e-6;

int_fields = { ...
    "connectivity", ...
    "faces", ...
    "offsets", ...
    "types", ...
    "faceoffsets" ...
};

examples = { ...

    struct( ...
        "name", "micp_mrst_opm", ...
        "ex_dir", "publications/paper_B", ...
        "vtk_dir", "vtk_micp_mrst_opm", ...
        "outputs", {{ ...
            struct( ...
                "name", "micp_mrst_opm", ...
                "generated", "states-00010.vtu", ...
                "reference", "micp_mrst_opm.vtu", ...
                "float_fields", {{"pressure", "m", "o", "u", ...
                                  "b", "c", "Coordinates"}} ...
            ) ...
        }} ...
    ), ...

    struct( ...
        "name", "micp_3Dfls", ...
        "ex_dir", "publications/paper_A", ...
        "vtk_dir", "vtk_micp_3Dfls", ...
        "outputs", {{ ...
            struct( ...
                "name", "micp_3Dfls", ...
                "generated", "states_3Dfls-00018.vtu", ...
                "reference", "micp_3Dfls.vtu", ...
                "float_fields", {{"pressure", "m", "o", "u", ...
                                  "b", "c", "Coordinates"}} ...
            ), ...
            struct( ...
                "name", "micp_3Dfls_CO2", ...
                "generated", "states_3Dfls_CO2-00001.vtu", ...
                "reference", "micp_3Dfls_CO2.vtu", ...
                "float_fields", {{"pressure", "s-1", "s-2", ...
                                  "Coordinates"}} ...
            ) ...
        }} ...
    ), ...

    struct( ...
        "name", "runMICP1DCase", ...
        "ex_dir", "examples", ...
        "vtk_dir", "vtk_1DCase", ...
        "outputs", {{ ...
            struct( ...
                "name", "runMICP1DCase", ...
                "generated", "states-00060.vtu", ...
                "reference", "runMICP1DCase.vtu", ...
                "float_fields", {{"pressure", "m", "o", "u", ...
                                  "b", "c", "Coordinates"}} ...
            ) ...
        }} ...
    ), ...

    struct( ...
        "name", "runMICP3DCase", ...
        "ex_dir", "examples", ...
        "vtk_dir", "vtk_3DCase", ...
        "outputs", {{ ...
            struct( ...
                "name", "runMICP3DCase_MICP", ...
                "generated", "statesMICP-00015.vtu", ...
                "reference", "runMICP3DCaseCO2_MICP.vtu", ...
                "float_fields", {{"pressure", "m", "o", "u", ...
                                  "b", "c", "Coordinates"}} ...
            ), ...
            struct( ...
                "name", "runMICP3DCase_CO2AfterMICP", ...
                "generated", "statesCO2afterMICP-00015.vtu", ...
                "reference", "runMICP3DCaseCO2_CO2AfterMICP.vtu", ...
                "float_fields", {{"pressure", "s-1", "s-2", ...
                                  "Coordinates"}} ...
            ), ...
            struct( ...
                "name", "runMICP3DCase_CO2BeforeMICP", ...
                "generated", "statesCO2beforeMICP-00015.vtu", ...
                "reference", "runMICP3DCaseCO2_CO2BeforeMICP.vtu", ...
                "float_fields", {{"pressure", "s-1", "s-2", ...
                                  "Coordinates"}} ...
            ) ...
        }} ...
    ), ...

    struct( ...
        "name", "micp_1Dfhs", ...
        "ex_dir", "publications/paper_A", ...
        "vtk_dir", "vtk_micp_1Dfhs", ...
        "outputs", {{ ...
            struct( ...
                "name", "micp_1Dfhs", ...
                "generated", "states-00010.vtu", ...
                "reference", "micp_1Dfhs.vtu", ...
                "float_fields", {{"pressure", "m", "o", "u", ...
                                  "b", "c", "Coordinates"}} ...
            ) ...
        }} ...
    ), ...

    struct( ...
        "name", "micp_2Dfhcs", ...
        "ex_dir", "publications/paper_A", ...
        "vtk_dir", "vtk_micp_2Dfhcs", ...
        "outputs", {{ ...
            struct( ...
                "name", "micp_2Dfhcs", ...
                "generated", "states_2Dfhcs-00005.vtu", ...
                "reference", "micp_2Dfhcs.vtu", ...
                "float_fields", {{"pressure", "m", "o", "u", ...
                                  "b", "c", "Coordinates"}} ...
            ) ...
        }} ...
    ), ...

    struct( ...
        "name", "micp_2Dfhrs", ...
        "ex_dir", "publications/paper_A", ...
        "vtk_dir", "vtk_micp_2Dfhrs", ...
        "outputs", {{ ...
            struct( ...
                "name", "micp_2Dfhrs", ...
                "generated", "states_2Dfhrs-00005.vtu", ...
                "reference", "micp_2Dfhrs.vtu", ...
                "float_fields", {{"pressure", "m", "o", "u", ...
                                  "b", "c", "Coordinates"}} ...
            ) ...
        }} ...
    ), ...

    struct( ...
        "name", "micp_2Dfls", ...
        "ex_dir", "publications/paper_A", ...
        "vtk_dir", "vtk_micp_2Dfls", ...
        "outputs", {{ ...
            struct( ...
                "name", "micp_2Dfls", ...
                "generated", "states_2Dfls-00018.vtu", ...
                "reference", "micp_2Dfls.vtu", ...
                "float_fields", {{"pressure", "m", "o", "u", ...
                                  "b", "c", "Coordinates"}} ...
            ), ...
            struct( ...
                "name", "micp_2Dfls_CO2", ...
                "generated", "states_2Dfls_CO2-00001.vtu", ...
                "reference", "micp_2Dfls_CO2.vtu", ...
                "float_fields", {{"pressure", "s-1", "s-2", ...
                                  "Coordinates"}} ...
            ) ...
        }} ...
    ), ...

    struct( ...
        "name", "micp_2Dfvrs", ...
        "ex_dir", "publications/paper_A", ...
        "vtk_dir", "vtk_micp_2Dfvrs", ...
        "outputs", {{ ...
            struct( ...
                "name", "micp_2Dfvrs_strategyA", ...
                "generated", "stateA-00002.vtu", ...
                "reference", "micp_2Dfvrs_strategya.vtu", ...
                "float_fields", {{"pressure", "m", "o", "u", ...
                                  "b", "c", "Coordinates"}} ...
            ), ...
            struct( ...
                "name", "micp_2Dfvrs_strategyB", ...
                "generated", "stateB-00002.vtu", ...
                "reference", "micp_2Dfvrs_strategyb.vtu", ...
                "float_fields", {{"pressure", "m", "o", "u", ...
                                  "b", "c", "Coordinates"}} ...
            ) ...
        }} ...
    ) ...

};

%% Download datasets required by the tests

mrstRoot = fullfile(orig, "..", "..");

mrstDataDirectory = fullfile( ...
    mrstRoot, "core", "examples", "data");

co2DatasetName = "CO2lab_Sampled_Tables";

co2DatasetDirectory = fullfile( ...
    mrstDataDirectory, co2DatasetName);

co2DatasetUrl = [ ...
    "https://www.sintef.no/contentassets/" ...
    "124f261f170947a6bc51dd76aea66129/" ...
    "co2lab_sampled_tables.zip"];

co2DatasetArchive = fullfile( ...
    mrstDataDirectory, "co2lab_sampled_tables.zip");

datasetAvailable = false;

if isfolder(co2DatasetDirectory)
    datasetContents = dir(co2DatasetDirectory);
    datasetNames = {datasetContents.name};

    datasetContents = datasetContents( ...
        ~ismember(datasetNames, {".", ".."}));

    datasetAvailable = ~isempty(datasetContents);
end

if ~datasetAvailable
    fprintf( ...
        "Downloading required dataset: %s...\n", ...
        co2DatasetName);

    if ~isfolder(mrstDataDirectory)
        mkdir(mrstDataDirectory);
    end

    if isfile(co2DatasetArchive)
        delete(co2DatasetArchive);
    end

    if isfolder(co2DatasetDirectory)
        rmdir(co2DatasetDirectory, "s");
    end

    curlCommand = sprintf( ...
        ['curl --location --fail --silent --show-error ' ...
         '--retry 5 --retry-delay 5 --retry-all-errors ' ...
         '--connect-timeout 30 --max-time 900 ' ...
         '--output "%s" "%s"'], ...
        co2DatasetArchive, co2DatasetUrl);

    [downloadStatus, downloadOutput] = system(curlCommand);

    if downloadStatus ~= 0
        if isfile(co2DatasetArchive)
            delete(co2DatasetArchive);
        end

        error( ...
            "Failed to download %s using curl:\n%s", ...
            co2DatasetName, downloadOutput);
    end

    archiveInformation = dir(co2DatasetArchive);

    if isempty(archiveInformation) || archiveInformation.bytes == 0
        delete(co2DatasetArchive);

        error( ...
            "The downloaded dataset archive is empty: %s", ...
            co2DatasetArchive);
    end

    extractionDirectory = tempname(mrstDataDirectory);
    mkdir(extractionDirectory);

    try
        unzip(co2DatasetArchive, extractionDirectory);
    catch extractionError
        if isfolder(extractionDirectory)
            rmdir(extractionDirectory, "s");
        end

        if isfile(co2DatasetArchive)
            delete(co2DatasetArchive);
        end

        rethrow(extractionError);
    end

    exactExtractedDirectory = fullfile( ...
        extractionDirectory, co2DatasetName);

    lowercaseExtractedDirectory = fullfile( ...
        extractionDirectory, "co2lab_sampled_tables");

    if isfolder(exactExtractedDirectory)
        movefile(exactExtractedDirectory, co2DatasetDirectory);

    elseif isfolder(lowercaseExtractedDirectory)
        movefile(lowercaseExtractedDirectory, co2DatasetDirectory);

    else
        extractedContents = dir(extractionDirectory);
        extractedNames = {extractedContents.name};

        extractedContents = extractedContents( ...
            ~ismember(extractedNames, {".", "..", "__MACOSX"}));

        extractedDirectories = extractedContents( ...
            [extractedContents.isdir]);

        if numel(extractedDirectories) == 1
            extractedDirectory = fullfile( ...
                extractionDirectory, ...
                extractedDirectories(1).name);

            movefile(extractedDirectory, co2DatasetDirectory);
        else
            mkdir(co2DatasetDirectory);

            for extractedIndex = 1 : numel(extractedContents)
                sourcePath = fullfile( ...
                    extractionDirectory, ...
                    extractedContents(extractedIndex).name);

                destinationPath = fullfile( ...
                    co2DatasetDirectory, ...
                    extractedContents(extractedIndex).name);

                movefile(sourcePath, destinationPath);
            end
        end
    end

    if isfolder(extractionDirectory)
        rmdir(extractionDirectory, "s");
    end

    if isfile(co2DatasetArchive)
        delete(co2DatasetArchive);
    end

    fprintf( ...
        "Dataset installed in:\n  %s\n", ...
        co2DatasetDirectory);
else
    fprintf( ...
        "Required dataset already available:\n  %s\n", ...
        co2DatasetDirectory);
end

%% Initialize MRST and test utilities

run("../../startup.m")

addpath(testsdir);

assert(~isempty(which("read_vtu")), ...
    "The read_vtu function is not available on the Octave path");

cd(orig);
rehash;

%% Run regression tests

for iexample = 1 : numel(examples)

    ex = examples{iexample};

    fprintf("Running %s...\n", ex.name);

    outdir = fullfile(orig, "test_outputs", ex.name);

    cd(orig);

    if isfolder(outdir)
        remove_output_paths(outdir);
        rmdir(outdir, "s");
    end

    mkdir(outdir);

    exampledir = fullfile(orig, ex.ex_dir);
    exampleFile = fullfile(exampledir, [ex.name ".m"]);
    copiedExampleFile = fullfile(outdir, [ex.name ".m"]);

    assert(isfile(exampleFile), ...
        sprintf("Example file not found: %s", exampleFile));

    copyfile(exampleFile, copiedExampleFile);

    run_example(copiedExampleFile, outdir);

    for icase = 1 : numel(ex.outputs)

        currentCase = ex.outputs{icase};

        fprintf("  Checking %s...\n", currentCase.name);

        generated = fullfile( ...
            outdir, ex.vtk_dir, currentCase.generated);

        reference = fullfile( ...
            testsdir, "reference", currentCase.reference);

        assert(isfile(generated), ...
            sprintf("%s/%s: generated VTU not found: %s", ...
            ex.name, currentCase.name, generated));

        assert(isfile(reference), ...
            sprintf("%s/%s: reference VTU not found: %s", ...
            ex.name, currentCase.name, reference));

        currentData = read_vtu(generated);
        referenceData = read_vtu(reference);

        % Integer and topology fields
        for fieldIndex = 1 : numel(int_fields)

            fieldName = int_fields{fieldIndex};

            assert(isfield(currentData, fieldName), ...
                sprintf( ...
                "%s/%s: missing field '%s' in generated VTU", ...
                ex.name, currentCase.name, fieldName));

            assert(isfield(referenceData, fieldName), ...
                sprintf( ...
                "%s/%s: missing field '%s' in reference VTU", ...
                ex.name, currentCase.name, fieldName));

            assert(isequal( ...
                currentData.(fieldName), ...
                referenceData.(fieldName)), ...
                sprintf( ...
                "%s/%s: field '%s' differs from reference", ...
                ex.name, currentCase.name, fieldName));
        end

        % Floating-point fields
        for fieldIndex = 1 : numel(currentCase.float_fields)

            fieldName = currentCase.float_fields{fieldIndex};

            assert(isfield(currentData, fieldName), ...
                sprintf( ...
                "%s/%s: missing field '%s' in generated VTU", ...
                ex.name, currentCase.name, fieldName));

            assert(isfield(referenceData, fieldName), ...
                sprintf( ...
                "%s/%s: missing field '%s' in reference VTU", ...
                ex.name, currentCase.name, fieldName));

            currentValues = currentData.(fieldName);
            referenceValues = referenceData.(fieldName);

            assert(numel(currentValues) == numel(referenceValues), ...
                sprintf( ...
                "%s/%s: field '%s' size mismatch (%d vs %d)", ...
                ex.name, currentCase.name, fieldName, ...
                numel(currentValues), numel(referenceValues)));

            difference = abs(currentValues - referenceValues);

            allowedError = ...
                absolute_tol + relative_tol .* abs(referenceValues);

            failedValues = difference > allowedError;

            if any(failedValues)
                maximumDifference = max(difference);
                maximumAllowedError = max(allowedError);
                numberOfFailures = nnz(failedValues);

                error(sprintf([ ...
                    "%s/%s: field '%s' exceeds tolerance; " ...
                    "%d of %d values failed, " ...
                    "maximum absolute error = %e, " ...
                    "maximum allowed error = %e"], ...
                    ex.name, currentCase.name, fieldName, ...
                    numberOfFailures, numel(difference), ...
                    maximumDifference, maximumAllowedError));
            end
        end

        fprintf("    OK\n");
    end
end

cd(orig);

fprintf("\nAll regression tests passed.\n");
