function param = run_opm_core_deck(deck, varargin)
   opt = struct('simulator', '', ...
                'deck_dir' , fileparts(mfilename('fullpath')));
   opt = merge_options(opt, varargin{:});

   if isempty(opt.simulator),
      opt.simulator = simcommand(opm_dir(evalin('base', 'myself')), ...
                                 fullfile('examples', ...
                                          'sim_2p_incomp_reorder'));
   end

   param = struct('use_deck'                      , 'true'       , ...
                  'output'                        , 'true'       , ...
                  'output_dir'                    , ...
                  fullfile(opt.deck_dir, 'test_output')          , ...
                  'use_pside'                     , 'false'      , ...
                  'linsolver'                     , 'umfpack'    , ...
                  'nl_pressure_maxiter'           , '30'         , ...
                  'nl_pressure_change_tolerance'  , '1'          , ...
                  'nl_pressure_residual_tolerance', '0'          , ...
                  'nl_maxiter'                    , '30'         , ...
                  'nl_tolerance'                  , '1e-7'       , ...
                  'num_transport_substeps'        , '1'          , ...
                  'use_segregation_split'         , 'false'      , ...
                  'deck_filename'                 , ...
                  fullfile(opt.deck_dir, 'data', ...
                           'test_deck', 'test_deck.DATA'));

   writeDeck(deck, fullfile(opt.deck_dir, 'data','test_deck'));

   % Run C OPM code
   run_opm_core(param, opt.simulator);

   param = paramToStruct(fullfile(param.output_dir, ...
                                  'simulation.param'));
end
