function names = getNorthSeaNames()
% Returns the formation names present in the North Sea.

names = {   'Brentgrp',...
            'Brynefm',...
            'Sleipnerfm',...
            'Sognefjordfm',...
            'Fensfjordfm',...
            'Krossfjordfm',...
            'Huginfmeast',...
            'Huginfmwest',...
            'Sandnesfm',...
            'Ulafm',...
            'Cookfm',...
            'Dunlingp',...
            'Gassumfm',...
            'Johansenfm',...
            'Paleocene'...
            'Pliocenesand',...
            'Skadefm',...
            'Statfjordfm',...
            'Utsirafm'      };


end

