function names = getNorwegianSeaNames()
% Returns the formation names present in the Norwegian Sea.
%


names = {   'Arefm',...
            'Rorfm',...
            'Notfm',...
            'Ilefm',...
            'Garnfm',...
            'Tiljefm'   }; 

end

