function [m, grad_m, int_m] = retrieveMonomials(k)

if k == 1
    
m      = @(X) ...
         [ones(size(X,1),1) , ...   %   (0,0)
          X(:,1)            , ...   %   (1,0)
          X(:,2)            ];

grad_m = @(X) ...
         [ones(size(X,1),1)    , zeros(size(X,1),1); ...
          zeros(size(X,1),1)   , ones(size(X,1),1) ];

int_m  = @(X) ...
         [X(:,1)                , ...
          X(:,1).^2/2           , ...
          X(:,1).*X(:,2)        ];
      
end

if k == 2
    
m      = @(X) ...
         [ones(size(X,1),1) , ...   %   (0,0)
          X(:,1)            , ...   %   (1,0)
          X(:,2)            , ...   %   (0,1)
          X(:,1).^2         , ...   %   (2,0)
          X(:,1).*X(:,2)    , ...   %   (1,1)
          X(:,2).^2         , ...   %   (0,2) 
                            ];

grad_m = @(X) ...
         [ones(size(X,1),1)    , zeros(size(X,1),1); ...
          zeros(size(X,1),1)   , ones(size(X,1),1) ; ...
          X(:,1)*2             , zeros(size(X,1),1); ...
          X(:,2)               , X(:,1)            ; ...
          zeros(size(X,1),1)   , X(:,2)*2          ];

int_m  = @(X) ...
         [X(:,1)                , ...
          X(:,1).^2/2           , ...
          X(:,1).*X(:,2)        , ...
          X(:,1).^3/3           , ...
          X(:,1).^2.*X(:,2)/2   , ...
          X(:,1).*X(:,2).^2     ];
      
end