function a = addSecondAxis(cur, offset)

    % a = copyobj(cur, gcf);
    % set(a, 'YAxisLocation', 'right');
    % set(a, 'YLim', get(cur, 'Ylim') - offset);
    
    a = axes('position', get(cur, 'position'), ...
             'YAxisLocation' ,'Right', ...
             'XTick', [], ...
             'color','none', ...
             'YDir', get(cur, 'YDir'),...
             'YLim', get(cur, 'YLim') - offset);
    ylabel(get(get(cur, 'YLabel'), 'string'));
end
