function [m, grad_m, int_m] = retrieve3Dmonomials(k)

m3D = @(X) [ones(size(X,1),1), ...
                (X(:,1)-Kc(1))/hK, ...
                (X(:,2)-Kc(2))/hK, ...
                (X(:,3)-Kc(3))/hK, ...
                (X(:,1)-Kc(1)).^2/hK^2, ...
                (X(:,1)-Kc(1)).*(X(:,2)-Kc(2))/hK^2, ...
                (X(:,1)-Kc(1)).*(X(:,3)-Kc(3))/hK^2, ...
                (X(:,2)-Kc(2)).^2/hK^2, ...
                (X(:,2)-Kc(2)).*(X(:,3)-Kc(3))/hK^2, ...
                (X(:,3)-Kc(3)).^2/hK^2];