function G = voronoiCube(n,gridLim)

% Sett the convex boundary
boundary = [0,          0         , 0         ; ...
            gridLim(1), 0         , 0         ; ...
            gridLim(1), gridLim(2), 0         ; ...
            0         , gridLim(2), 0         ; ...
            0         , 0         , gridLim(3); ...
            gridLim(1), 0         , gridLim(3); ...
            gridLim(1), gridLim(2), gridLim(3); ...
            0         , gridLim(2), gridLim(3)];
% Generate random seed points
pts = bsxfun(@times, rand(n,3), gridLim);
% Generate voronoi grid
G = voronoi3D(pts, boundary);

end

