function fw = WP_fractional_flow_teoretical(fluid,state)

fw =  1./...
    ( 1+  ( (fluid.krOW(state.s(:,2)).*fluid.muW(state.pressure))./...
            (fluid.krW( state.s(:,1)).*fluid.muO(state.pressure)) )    );