function opt = cartesianGridDefaults
    
    % opt = struct('cartDims',   [2 1 1],        ...
    %              'porosity',    0.1, ...
    %              'perm',        100 * milli * darcy, ...
    %              'physDims',   [2000 1000 100], ...
    %              'topo',       0);
        
    %% PARAMETERS FOR A 50x1 GRID

    %topo = -30 * sin([1:51]'/51 * 4*pi);
    %topo = - 100 * [1:51]'/51;

    opt = struct('cartDims',   [51 1 1],        ...
                 'porosity',    0.1, ...
                 'perm',        100 * milli * darcy, ...
                 'physDims',   [5000 3000 100], ...
                 'topo',       0);

 
        
    %% PARAMETERS FOR A 20x20 GRID        

    % topo_1D = sin([1:21]'/21 * pi);    
    % topo = -20 * topo_1D * topo_1D';    
    
    % opt = struct('cartDims',   [20 20 10],        ...
    %              'porosity',    0.1, ...
    %              'perm',        100 * milli * darcy, ...
    %              'physDims',   [5000 3000 100], ...
    %              'topo',       topo);

        
        
        
end
