function rts = getModuleRegressionTests()
%Return regression tests for the geothermal module.

    mrstModule add mrst-testing

    rts = {
        MRSTRegressionTest(@qfs_geothermal, ...
            'group', 'geothermal', 'name', 'qfs')
        MRSTRegressionTest(@qfs_geothermal, ...
            'group', 'geothermal', 'name', 'qfs_nacl', ...
            'setupArgs', {'NaCl', true})
        MRSTRegressionTest(@small_egs_geothermal, ...
            'group', 'geothermal', 'name', 'small_egs')
        MRSTRegressionTest(@fivespot_geothermal, ...
            'group', 'geothermal', 'name', 'fivespot')
        MRSTRegressionTest(@convection_geothermal, ...
            'group', 'geothermal', 'name', 'convection')
        MRSTRegressionTest(@convection_geothermal, ...
            'group', 'geothermal', 'name', 'convection_mass', ...
            'setupArgs', {'massInjection', true})
        MRSTRegressionTest(@htates_geothermal, ...
            'group', 'geothermal', 'name', 'htates')
    };
end
