function fluid = makeMyFluid(Gt, rock, seainfo)

    fmName = 'Utsirafm';
    surface_pressure = 0;
    
    % Set-up fluid:
    % p_init and T_ref is function of caprock depth, which impacts fluid
    gravity on;
    p_init = seainfo.water_density * norm(gravity()) * Gt.cells.z + surface_pressure;
    press_deviation = 0;
    p_init = p_init .* (1+press_deviation/100);
    T_ref = 273.15 + seainfo.seafloor_temp + ...
        seainfo.temp_gradient * (Gt.cells.z - seainfo.seafloor_depth) / 1000; % Kelvin

    fluid = makeVEFluid(Gt, rock, 'sharp interface'                    , ...
           'fixedT'       , T_ref                                      , ...
           'residual'     , [seainfo.res_sat_wat, seainfo.res_sat_co2] , ...
           'wat_rho_ref'  , seainfo.water_density                      , ...
           'co2_rho_ref'  , seainfo.rhoCref                            , ... 
           'wat_rho_pvt'  , [4.3e-5/barsa, mean(p_init)]               , ...
           'co2_rho_pvt'  , [[0.1, 400] * mega * Pascal, [4 250] + 274], ... 
           'wat_mu_ref'   , seainfo.water_mu                           , ...
           'co2_mu_pvt'   , [[0.1, 400] * mega * Pascal, [4 250] + 274], ... 
           'pvMult_fac'   , 1e-5/barsa                                 , ...
           'pvMult_p_ref' , mean(p_init)                               , ...
           'dissolution'  , false                                      , ...
           'dis_rate'     , []                                         , ...
           'dis_max'      , []                                         , ...
           'surf_topo'    , 'smooth'                                   , ...
           'top_trap'     , []);

end