%% Figure 1

% Not generated by Matlab

%% Figure 2

% First, run the first 7 lines of 
showNodeTrapsCalc;

% Then, set a breakpoint in computeNodeTraps:
dbstop in computeNodeTraps at 93;

% Then run line 12 of 
showNodeTrapsCalc;

% When the breakpoint in computeNodeTraps, run the remaining lines of
showNodeTrapsCalc;

%% Figure 3

% Not generated by Matlab

%% Figure 4

% no script available

%% Figure 5 and 6

trappingExample1;

%% Figure 7 and 8 (and table 1)

describeAtlas;


%% Figure 9

trapsHuginWest;

%% Figure 10 and 11

trapsJohansen;

%% Figure 12

showIGEMS;

%% Figure 13

trapsIGEMS;

%% Figure 14

fillTreeIGEMS;

%% Figure 15

optimizationExample;
