function amg_opt = getAMGCLMexStruct(varargin)
    amg_opt = struct('preconditioner', 'amg', ...
                     'coarsening',     'smoothed_aggregation', ...
                     'relaxation',     'spai0', ...
                     's_relaxation',   'ilu0', ...
                     'solver',         'bicgstab', ...
                     'block_size',     0, ...
                     'tolerance',      1e-6, ...
                     'use_drs',        true, ...
                     'drs_eps_ps',     0.02, ...
                     'drs_eps_dd',     0.2, ...
                     'coarse_enough',  -1, ...
                     'direct_coarse',  false, ...
                     'max_levels',     -1, ...
                     'ncycle',         1, ...
                     'npre',           1, ...
                     'npost',          1, ...
                     'pre_cycles',     1, ...
                     'maxIterations',   0);
    amg_opt = merge_options(amg_opt, varargin{:});
    % Translate into codes
    amg_opt.preconditioner = translateOptionsAMGCL('preconditioner', amg_opt.preconditioner);
    amg_opt.coarsening = translateOptionsAMGCL('coarsening', amg_opt.coarsening);
    amg_opt.relaxation = translateOptionsAMGCL('relaxation', amg_opt.relaxation);
    amg_opt.s_relaxation = translateOptionsAMGCL('relaxation', amg_opt.s_relaxation);
    amg_opt.solver = translateOptionsAMGCL('solver', amg_opt.solver);

end