test_solver: test_solver.cpp mrst_duneistl.hpp 
	g++ -g -o test_solver test_solver.cpp -I/Users/atgeirr/duneinstallhack/include -std=c++14 -L/Users/atgeirr/duneinstallhack/lib -lstdc++ -lm -ldunecommon
