%% Workflow example for MICP treatment of a 3D leakage system
%
% This example demonstrates a complete workflow for creating, running, and
% analyzing a three-dimensional flow system containing a vertical leakage
% path. The workflow consists of three simulations:
%
% 1. CO2 injection before MICP treatment.
% 2. MICP treatment of the leakage path.
% 3. CO2 injection after MICP treatment.
%
% The CO2 simulations use `TwoPhaseWaterGasModel` from the MRST `co2lab`
% module. The MICP treatment uses `MICPModel` from the `ad-micp` module.
%
% For details on the MICP model, see:
%
% Landa-Marbán, D., Tveit, S., Kumar, K., Gasda, S.E., 2021.
% Practical approaches to study microbially induced calcite precipitation
% at the field scale. International Journal of Greenhouse Gas Control 106,
% 103256.
%
% https://doi.org/10.1016/j.ijggc.2021.103256

% Required modules
mrstModule add ad-blackoil ad-core ad-micp ad-props co2lab upr

%% Reservoir geometry, properties, and model parameters
%
% The domain is 200 m long, 180 m wide, and 160 m high. It contains a
% lower aquifer, a vertical leakage path through the caprock, and an upper
% aquifer. Cells outside the leakage path are removed from the caprock
% interval.
%
% The leakage path is centered at (0, 0). The computational grid is refined
% around the leakage path and the injection well and coarsened away from
% these regions.

domainLength = 200;       % Reservoir length, m
domainWidth = 180;        % Reservoir width, m
topAquiferHeight = 30;    % Top aquifer height, m
leakageHeight = 100;      % Leakage interval height, m
bottomAquiferHeight = 30; % Bottom aquifer height, m

domainHeight = ...
    topAquiferHeight + leakageHeight + bottomAquiferHeight;

aquiferTopDepth = 1500;   % Depth of the top surface, m
leakageWidth = 1;         % Leakage-path width, m
wellXLocation = -20;      % Well x-coordinate relative to leakage, m

minimumGridSize = leakageWidth;
mediumGridSize = 3;
maximumGridSize = domainLength;
transitionRadius = 10;

% Fix the random seed to improve mesh reproducibility.
rand('seed', 0);
randn('seed', 0);

distanceFunction = @(points) drectangle( ...
    points, ...
    -domainLength / 2, ...
    domainLength / 2, ...
    -domainWidth / 2, ...
    domainWidth / 2);

sizeFunction = @(points) min( ...
    min( ...
    mediumGridSize + ...
    0.3 .* abs(dcircle(points, wellXLocation, 0, 0)), ...
    mediumGridSize) .* ...
    (abs(dcircle(points, wellXLocation, 0, 0)) < ...
    transitionRadius) + ...
    min( ...
    mediumGridSize + ...
    0.3 .* abs(dcircle( ...
    points, wellXLocation, 0, transitionRadius)), ...
    maximumGridSize) .* ...
    (abs(dcircle(points, wellXLocation, 0, 0)) >= ...
    transitionRadius), ...
    min( ...
    minimumGridSize + ...
    0.3 .* abs(dcircle(points, 0, 0, 0)), ...
    mediumGridSize) .* ...
    (abs(dcircle(points, 0, 0, 0)) < ...
    transitionRadius) + ...
    min( ...
    mediumGridSize + ...
    0.3 .* abs(dcircle(points, 0, 0, transitionRadius)), ...
    maximumGridSize) .* ...
    (abs(dcircle(points, 0, 0, 0)) >= ...
    transitionRadius));

boundingBox = [ ...
    -domainLength / 2, -domainWidth / 2; ...
     domainLength / 2,  domainWidth / 2];

fixedPoints = [ ...
    -domainLength / 2, -domainWidth / 2; ...
     domainLength / 2, -domainWidth / 2; ...
    -domainLength / 2,  domainWidth / 2; ...
     domainLength / 2,  domainWidth / 2; ...
     0,                 0];

[gridPoints, gridTriangles] = distmesh2d( ...
    distanceFunction, ...
    sizeFunction, ...
    minimumGridSize, ...
    boundingBox, ...
    fixedPoints, ...
    true);

close

verticalCoordinates = [ ...
    0, ...
    3, ...
    10, ...
    topAquiferHeight : 10 : ...
    topAquiferHeight + leakageHeight, ...
    topAquiferHeight + leakageHeight + 3, ...
    topAquiferHeight + leakageHeight + 10, ...
    domainHeight];

verticalCoordinates = unique(verticalCoordinates, 'stable');

numberOfLayers = numel(verticalCoordinates) - 1;

G = makeLayeredGrid( ...
    pebi(triangleGrid(gridPoints, gridTriangles)), ...
    numberOfLayers);

nodesPerLayer = G.nodes.num / numel(verticalCoordinates);

nodesPerLayer = round(nodesPerLayer);

for layerIndex = 1 : numel(verticalCoordinates)
    firstNode = 1 + nodesPerLayer * (layerIndex - 1);
    lastNode = nodesPerLayer * layerIndex;

    G.nodes.coords(firstNode : lastNode, 3) = ...
        verticalCoordinates(layerIndex) + aquiferTopDepth;
end

G = computeGeometry(G);

cellCentroids = G.cells.centroids;

caprockCellsOutsideLeakage = ...
    cellCentroids(:, 1) .^ 2 + ...
    cellCentroids(:, 2) .^ 2 > ...
    (minimumGridSize / 2) ^ 2 & ...
    cellCentroids(:, 3) < ...
    aquiferTopDepth + topAquiferHeight + leakageHeight & ...
    cellCentroids(:, 3) > ...
    aquiferTopDepth + topAquiferHeight;

G = removeCells(G, caprockCellsOutsideLeakage);
G = computeGeometry(G);

cellCentroids = G.cells.centroids;
cellTemplate = ones(G.cells.num, 1);

%% Rock properties

initialPermeability = 2e-14 .* cellTemplate;

% Identify the cells belonging to the vertical leakage path and assign a
% higher initial permeability.
leakageCellIndices = G.cells.indexMap;

leakageCellIndices = leakageCellIndices( ...
    cellCentroids(:, 1) .^ 2 + ...
    cellCentroids(:, 2) .^ 2 < ...
    (minimumGridSize / 2) ^ 2 & ...
    cellCentroids(:, 3) < ...
    aquiferTopDepth + domainHeight - bottomAquiferHeight & ...
    cellCentroids(:, 3) > ...
    aquiferTopDepth + topAquiferHeight);

activeCellIndices = G.cells.indexMap;
isLeakageCell = ismember(activeCellIndices, leakageCellIndices);

initialPermeability(isLeakageCell) = 1e-12;

initialPorosity = 0.15;

rock = makeRock( ...
    G, initialPermeability, initialPorosity);

%% MICP fluid and model properties

fluid.muw = 2.535e-4;          % Water viscosity, Pa s
fluid.bW = @(pressure) ...
    0 .* pressure + 1;         % Water formation volume factor, [-]
fluid.rhoWS = 1045;            % Water density, kg/m^3

fluid.rho_b = 35;              % Biofilm density, kg/m^3
fluid.rho_c = 2710;            % Calcite density, kg/m^3
fluid.k_str = 2.6e-10;         % Detachment coefficient, m/(Pa s)
fluid.diffm = 2.1e-9;          % Microorganism diffusion, m^2/s
fluid.diffo = 2.32e-9;         % Oxygen diffusion, m^2/s
fluid.diffu = 1.38e-9;         % Urea diffusion, m^2/s
fluid.alphaL = 1e-3;           % Longitudinal dispersivity, m
fluid.alphaT = 4e-4;           % Transverse dispersivity, m
fluid.eta = 3;                 % Permeability fitting factor, [-]
fluid.k_o = 2e-5;              % Oxygen half-velocity constant, kg/m^3
fluid.k_u = 21.3;              % Urea half-velocity constant, kg/m^3
fluid.mu = 4.17e-5;            % Maximum growth rate, 1/s
fluid.mu_u = 0.0161;           % Maximum urease utilization rate, 1/s
fluid.k_a = 8.51e-7;           % Microorganism attachment rate, 1/s
fluid.k_d = 3.18e-7;           % Microorganism death rate, 1/s
fluid.Y = 0.5;                 % Growth yield coefficient, [-]
fluid.Yuc = 1.67;              % Calcite-to-urea yield coefficient, [-]
fluid.F = 0.5;                 % Oxygen consumption factor, [-]
fluid.crit = 0.1;              % Critical porosity, [-]
fluid.kmin = 1e-20;            % Minimum permeability, m^2

% Porosity-permeability relationship. Clipping the normalized porosity
% avoids evaluating fractional powers of negative values if the exponent
% is changed to a noninteger value.
normalizedPorosity = @(porosity) max( ...
    (porosity - fluid.crit) ./ ...
    (initialPorosity - fluid.crit), ...
    0);

fluid.K = @(porosity) max( ...
    (initialPermeability .* ...
    normalizedPorosity(porosity) .^ fluid.eta + ...
    fluid.kmin) .* ...
    initialPermeability ./ ...
    (initialPermeability + fluid.kmin), ...
    fluid.kmin);

% Compatibility fields required by the oil-water parent model.
fluid.bO = fluid.bW;
fluid.rhoOS = fluid.rhoWS;

%% Gravity

gravity reset
gravity on

gravityMagnitude = norm(gravity);

%% CO2 assessment before MICP treatment
%
% Simulate CO2 injection before MICP treatment using
% `TwoPhaseWaterGasModel`.

initialCO2State.pressure = ...
    fluid.rhoWS .* gravityMagnitude .* cellCentroids(:, 3);

initialCO2State.s = ...
    repmat([1, 0], G.cells.num, 1);

co2Properties = CO2props();

referencePressure = 15 * mega * Pascal;
referenceTemperature = 70 + 273.15;

co2Density = co2Properties.rho( ...
    referencePressure, referenceTemperature);

co2Compressibility = ...
    co2Properties.rhoDP( ...
    referencePressure, referenceTemperature) ./ co2Density;

waterCompressibility = 0;
rockCompressibility = 0;

co2Viscosity = ...
    co2Properties.mu( ...
    referencePressure, referenceTemperature) .* ...
    Pascal .* second;

co2Fluid = initSimpleADIFluid( ...
    'phases', 'WG', ...
    'mu', [fluid.muw, co2Viscosity], ...
    'rho', [fluid.rhoWS, co2Density], ...
    'pRef', referencePressure, ...
    'c', [waterCompressibility, co2Compressibility], ...
    'cR', rockCompressibility, ...
    'n', [2, 2]);

% Relative permeability curves
residualWaterSaturation = 0.27;
residualCO2Saturation = 0;

baseWaterRelativePermeability = co2Fluid.krW;
baseCO2RelativePermeability = co2Fluid.krG;

co2Fluid.krW = @(saturation) ...
    baseWaterRelativePermeability(max( ...
    (saturation - residualWaterSaturation) ./ ...
    (1 - residualWaterSaturation), ...
    0));

co2Fluid.krG = @(saturation) ...
    baseCO2RelativePermeability(max( ...
    (saturation - residualCO2Saturation) ./ ...
    (1 - residualCO2Saturation), ...
    0));

% Capillary-pressure curve
entryPressure = 5 * kilo * Pascal;

waterGasCapillaryPressure = @(waterSaturation) ...
    entryPressure .* waterSaturation .^ (-1 / 2);

co2Fluid.pcWG = @(gasSaturation) ...
    waterGasCapillaryPressure(max( ...
    (1 - gasSaturation - residualWaterSaturation) ./ ...
    (1 - residualWaterSaturation), ...
    1e-5));

co2ModelBeforeMICP = ...
    TwoPhaseWaterGasModel(G, rock, co2Fluid, 0, 0);

%% CO2 injection well

co2InjectionRate = 80 / day;
wellRadius = 0.15;

[~, nearestWellCell] = min( ...
    (cellCentroids(:, 1) - wellXLocation) .^ 2 + ...
    cellCentroids(:, 2) .^ 2);

allCellIndices = (1 : G.cells.num)';

co2WellCells = allCellIndices( ...
    abs(cellCentroids(:, 1) - ...
    cellCentroids(nearestWellCell, 1)) < eps & ...
    abs(cellCentroids(:, 2) - ...
    cellCentroids(nearestWellCell, 2)) < eps & ...
    cellCentroids(:, 3) > ...
    aquiferTopDepth + domainHeight - bottomAquiferHeight);

co2Well = addWell( ...
    [], ...
    G, ...
    rock, ...
    co2WellCells, ...
    'Type', 'rate', ...
    'Comp_i', [0, 1], ...
    'Val', co2InjectionRate, ...
    'Radius', wellRadius);

%% Open boundary conditions

boundaryFaceIndices = boundaryFaces(G);

openBoundaryFaces = boundaryFaceIndices( ...
    abs(G.faces.normals(boundaryFaceIndices, 1)) > eps & ...
    (G.faces.centroids(boundaryFaceIndices, 1) < ...
    -maximumGridSize / 4 | ...
    G.faces.centroids(boundaryFaceIndices, 1) > ...
    domainLength / 2 - maximumGridSize / 4));

boundaryPressure = ...
    G.faces.centroids(openBoundaryFaces, 3) .* ...
    fluid.rhoWS .* gravityMagnitude;

co2BoundaryConditions = addBC( ...
    [], ...
    openBoundaryFaces, ...
    'pressure', boundaryPressure, ...
    'sat', [1, 0]);

%% CO2 injection schedule

co2TimeStep = day;
numberOfCO2Steps = 30;

if exist('AD_MICP_TEST', 'var')
    numberOfCO2Steps = 15;
end

co2Timesteps = ...
    repmat(co2TimeStep, numberOfCO2Steps, 1);

co2Schedule = simpleSchedule( ...
    co2Timesteps, ...
    'W', co2Well, ...
    'bc', co2BoundaryConditions);

%% Simulate CO2 injection before treatment

if exist('OCTAVE_VERSION', 'builtin') ~= 0
    [~, statesCO2beforeMICP] = simulateScheduleAD( ...
        initialCO2State, ...
        co2ModelBeforeMICP, ...
        co2Schedule);
else
    co2PlotFunction = getPlotAfterStepCO2( ...
        initialCO2State, ...
        co2ModelBeforeMICP, ...
        340, ...
        20);

    [~, statesCO2beforeMICP] = simulateScheduleAD( ...
        initialCO2State, ...
        co2ModelBeforeMICP, ...
        co2Schedule, ...
        'afterStepFn', co2PlotFunction);
end

%% Calculate leakage before MICP treatment
%
% The leakage rate is evaluated through the horizontal face at the base of
% the leakage path.

faceCentroids = G.faces.centroids;
allFaceIndices = (1 : G.faces.num)';

leakageElevation = ...
    aquiferTopDepth + topAquiferHeight + leakageHeight;

leakageFaceTolerance = 0.01;

leakageFaces = allFaceIndices( ...
    faceCentroids(:, 3) < ...
    leakageElevation + leakageFaceTolerance & ...
    faceCentroids(:, 3) > ...
    leakageElevation - leakageFaceTolerance & ...
    faceCentroids(:, 1) .^ 2 + ...
    faceCentroids(:, 2) .^ 2 < ...
    (minimumGridSize / 2) ^ 2);

leakageBeforeMICP = zeros(numberOfCO2Steps, 1);

for stepIndex = 1 : numberOfCO2Steps
    leakageBeforeMICP(stepIndex) = abs( ...
        statesCO2beforeMICP{stepIndex}.flux(leakageFaces, 2));
end

%% MICP treatment strategy
%
% Each row of `injectionStrategy` contains:
%
%   1. Phase duration, s
%   2. Simulation timestep, s
%   3. Injection rate, m^3/s
%   4. Microorganism concentration, kg/m^3
%   5. Oxygen concentration, kg/m^3
%   6. Urea concentration, kg/m^3

activeTimeStep = hour;
shutInTimeStep = 5 * hour;

injectionStrategy = [ ...
    15 * hour, activeTimeStep, 0.3, 0.01, 0,    0; ...
    11 * hour, activeTimeStep, 0.3, 0,    0,    0; ...
    75 * hour, shutInTimeStep, 0,  0,    0,    0; ...
    30 * hour, activeTimeStep, 0.3, 0,    0.04, 0; ...
     5 * hour, activeTimeStep, 0.3, 0,    0,    0; ...
    25 * hour, shutInTimeStep, 0,  0,    0,    0; ...
    40 * hour, activeTimeStep, 0.3, 0,    0,   60; ...
    10 * hour, activeTimeStep, 0.3, 0,    0,    0; ...
    40 * hour, shutInTimeStep, 0,  0,    0,    0];

if exist('AD_MICP_TEST', 'var')
    injectionStrategy = [ ...
        15 * hour, activeTimeStep, 0.3, 0.01, 0.04, 60];
end

numberOfTreatmentPhases = size(injectionStrategy, 1);

%% MICP injection wells
%
% The treatment well has two completions. MICP components are injected
% through the upper completion, while the lower completion injects water.

upperWellFraction = 3 / bottomAquiferHeight;
lowerWellFraction = 1 - upperWellFraction;

upperTreatmentCells = allCellIndices( ...
    abs(cellCentroids(:, 1) - ...
    cellCentroids(nearestWellCell, 1)) < eps & ...
    abs(cellCentroids(:, 2) - ...
    cellCentroids(nearestWellCell, 2)) < eps & ...
    cellCentroids(:, 3) > ...
    aquiferTopDepth + domainHeight - bottomAquiferHeight & ...
    cellCentroids(:, 3) < ...
    aquiferTopDepth + domainHeight - ...
    lowerWellFraction * bottomAquiferHeight);

lowerTreatmentCells = allCellIndices( ...
    abs(cellCentroids(:, 1) - ...
    cellCentroids(nearestWellCell, 1)) < eps & ...
    abs(cellCentroids(:, 2) - ...
    cellCentroids(nearestWellCell, 2)) < eps & ...
    cellCentroids(:, 3) > ...
    aquiferTopDepth + domainHeight - ...
    lowerWellFraction * bottomAquiferHeight);

treatmentWell = addWell( ...
    [], ...
    G, ...
    rock, ...
    upperTreatmentCells, ...
    'Type', 'rate', ...
    'Comp_i', [1, 0], ...
    'Val', upperWellFraction * injectionStrategy(1, 3), ...
    'Radius', wellRadius);

treatmentWell = addWell( ...
    treatmentWell, ...
    G, ...
    rock, ...
    lowerTreatmentCells, ...
    'Type', 'rate', ...
    'Comp_i', [1, 0], ...
    'Val', lowerWellFraction * injectionStrategy(1, 3), ...
    'Radius', wellRadius);

for completionIndex = 1 : numel(treatmentWell)
    treatmentWell(completionIndex).m = 0;
    treatmentWell(completionIndex).o = 0;
    treatmentWell(completionIndex).u = 0;
end

treatmentWell(1).m = injectionStrategy(1, 4);
treatmentWell(1).o = injectionStrategy(1, 5);
treatmentWell(1).u = injectionStrategy(1, 6);

% The MICP injection well is not located on the model boundary.
G.injectionwellonboundary = 0;

%% MICP boundary conditions

micpBoundaryConditions = co2BoundaryConditions;

numberOfBoundaryFaces = ...
    size(micpBoundaryConditions.sat, 1);

micpBoundaryConditions.m = ...
    zeros(numberOfBoundaryFaces, 1);
micpBoundaryConditions.o = ...
    zeros(numberOfBoundaryFaces, 1);
micpBoundaryConditions.u = ...
    zeros(numberOfBoundaryFaces, 1);
micpBoundaryConditions.b = ...
    zeros(numberOfBoundaryFaces, 1);
micpBoundaryConditions.c = ...
    zeros(numberOfBoundaryFaces, 1);

%% Construct MICP treatment schedule

stepsPerPhase = ...
    injectionStrategy(:, 1) ./ injectionStrategy(:, 2);

stepsPerPhase = round(stepsPerPhase);
totalNumberOfTreatmentSteps = sum(stepsPerPhase);

treatmentTimesteps = ...
    zeros(totalNumberOfTreatmentSteps, 1);

treatmentControlIndices = ...
    zeros(totalNumberOfTreatmentSteps, 1);

firstStep = 1;

for phaseIndex = 1 : numberOfTreatmentPhases
    lastStep = ...
        firstStep + stepsPerPhase(phaseIndex) - 1;

    treatmentTimesteps(firstStep : lastStep) = ...
        injectionStrategy(phaseIndex, 2);

    treatmentControlIndices(firstStep : lastStep) = ...
        phaseIndex;

    firstStep = lastStep + 1;
end

micpSchedule = simpleSchedule( ...
    treatmentTimesteps, ...
    'W', treatmentWell, ...
    'bc', micpBoundaryConditions);

baseControl = micpSchedule.control(1);

micpSchedule.control = repmat( ...
    baseControl, numberOfTreatmentPhases, 1);

for phaseIndex = 1 : numberOfTreatmentPhases
    micpSchedule.control(phaseIndex).W(1).val = ...
        upperWellFraction * injectionStrategy(phaseIndex, 3);

    micpSchedule.control(phaseIndex).W(2).val = ...
        lowerWellFraction * injectionStrategy(phaseIndex, 3);

    micpSchedule.control(phaseIndex).W(1).m = ...
        injectionStrategy(phaseIndex, 4);

    micpSchedule.control(phaseIndex).W(1).o = ...
        injectionStrategy(phaseIndex, 5);

    micpSchedule.control(phaseIndex).W(1).u = ...
        injectionStrategy(phaseIndex, 6);
end

micpSchedule.step.control = treatmentControlIndices;
micpSchedule.step.val = treatmentTimesteps;

% Maximum injected concentrations used for state limiting and plotting.
fluid.Comax = max(injectionStrategy(:, 5));
fluid.Cumax = max(injectionStrategy(:, 6));

%% Create MICP model and initial state

micpModel = MICPModel(G, rock, fluid);

initialMICPState = initialCO2State;
initialMICPState.m = zeros(G.cells.num, 1);
initialMICPState.o = zeros(G.cells.num, 1);
initialMICPState.u = zeros(G.cells.num, 1);
initialMICPState.b = zeros(G.cells.num, 1);
initialMICPState.c = zeros(G.cells.num, 1);

%% Simulate MICP treatment

if exist('OCTAVE_VERSION', 'builtin') ~= 0
    [~, statesMICP] = simulateScheduleAD( ...
        initialMICPState, ...
        micpModel, ...
        micpSchedule);
else
    micpPlotFunction = getPlotAfterStepMICP( ...
        initialMICPState, micpModel, 340, 20);

    [~, statesMICP] = simulateScheduleAD( ...
        initialMICPState, ...
        micpModel, ...
        micpSchedule, ...
        'afterStepFn', micpPlotFunction);
end

%% CO2 assessment after MICP treatment

porosityAfterMICP = max( ...
    micpModel.referencePorosity - ...
    statesMICP{end}.b - statesMICP{end}.c, ...
    micpModel.minimumPorosity);

permeabilityAfterMICP = ...
    fluid.K(porosityAfterMICP);

permeabilityAfterMICP = max( ...
    permeabilityAfterMICP, fluid.kmin);

treatedRock = makeRock( ...
    G, permeabilityAfterMICP, porosityAfterMICP);

co2ModelAfterMICP = ...
    TwoPhaseWaterGasModel(G, treatedRock, co2Fluid, 0, 0);

% Recreate the CO2 well using the treated rock so that the well index is
% consistent with the post-treatment permeability.
co2WellAfterMICP = addWell( ...
    [], ...
    G, ...
    treatedRock, ...
    co2WellCells, ...
    'Type', 'rate', ...
    'Comp_i', [0, 1], ...
    'Val', co2InjectionRate, ...
    'Radius', wellRadius);

co2ScheduleAfterMICP = simpleSchedule( ...
    co2Timesteps, ...
    'W', co2WellAfterMICP, ...
    'bc', co2BoundaryConditions);

if exist('OCTAVE_VERSION', 'builtin') ~= 0
    [~, statesCO2afterMICP] = simulateScheduleAD( ...
        initialCO2State, ...
        co2ModelAfterMICP, ...
        co2ScheduleAfterMICP);
else
    co2PlotFunction = getPlotAfterStepCO2( ...
        initialCO2State, co2ModelAfterMICP, 340, 20);

    [~, statesCO2afterMICP] = simulateScheduleAD( ...
        initialCO2State, ...
        co2ModelAfterMICP, ...
        co2ScheduleAfterMICP, ...
        'afterStepFn', co2PlotFunction);
end

%% Calculate leakage after MICP treatment

leakageAfterMICP = zeros(numberOfCO2Steps, 1);

for stepIndex = 1 : numberOfCO2Steps
    leakageAfterMICP(stepIndex) = abs( ...
        statesCO2afterMICP{stepIndex}.flux(leakageFaces, 2));
end

%% Compare leakage before and after treatment

if ~exist('AD_MICP_TEST', 'var')
    timeInDays = ...
        cumsum(co2Timesteps) ./ day;

    figure;
    hold on

    plot( ...
        timeInDays, ...
        100 .* leakageBeforeMICP ./ co2InjectionRate, ...
        'Color', [1, 0.2, 0.2], ...
        'LineWidth', 9, ...
        'LineStyle', '-');

    plot( ...
        timeInDays, ...
        100 .* leakageAfterMICP ./ co2InjectionRate, ...
        'Color', [1, 0.5, 0], ...
        'LineWidth', 9, ...
        'LineStyle', '-');

    hold off

    legend( ...
        'Before MICP', ...
        'After MICP', ...
        'Location', 'southeast');

    xlabel('Time [d]');
    ylabel('CO$_2$ leakage rate/injection rate [\%]', ...
        'Interpreter', 'latex');

    grid on
end

%% Export and visualize results
%
% Export all three simulations to VTK format without changing the current
% working directory.

outputDirectory = fullfile(pwd, 'vtk_3DCase');

if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

co2BeforeOutput = fullfile( ...
    outputDirectory, 'statesCO2beforeMICP');

micpOutput = fullfile( ...
    outputDirectory, 'statesMICP');

co2AfterOutput = fullfile( ...
    outputDirectory, 'statesCO2afterMICP');

mrsttovtk( ...
    G, statesCO2beforeMICP, co2BeforeOutput, '%f');

mrsttovtk( ...
    G, statesMICP, micpOutput, '%f');

mrsttovtk( ...
    G, statesCO2afterMICP, co2AfterOutput, '%f');

fprintf( ...
    ['VTK results written to:\n' ...
     '  %s.pvd\n' ...
     '  %s.pvd\n' ...
     '  %s.pvd\n'], ...
    co2BeforeOutput, ...
    micpOutput, ...
    co2AfterOutput);

if exist('OCTAVE_VERSION', 'builtin') ~= 0
    return
end

%% Interactive visualization in MATLAB
mrstModule add mrst-gui
figure;
plotToolbar(G, statesMICP, 'field', 's:1', 'lockCaxis', true);
view(340, 20); axis tight; colorbar; caxis([0 1]);

%% Copyright notice
%{
Copyright 2021-2026, NORCE Research AS, Computational Geosciences and
Modeling.

This file is part of the ad-micp module.

ad-micp is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

ad-micp is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this file. If not, see <http://www.gnu.org/licenses/>.
%}
