function limiters = addLimiter(limiters, varargin)
    limiter = struct('type'     , 'tvb'    , ...
                     'variables', {{'s'}}  , ...
                     'limits'   , {{[0,1]}}, ...
                     'tol'      , 0        , ...
                     'function' , []       );
    limiter  = merge_options(limiter, varargin{:});
    limiters = [limiters; limiter];
end