function bic = eCPAreadBinaryInteraction(fluid, T)

na = fluid.names;
ncomp = numel(na);
bic = zeros(ncomp,ncomp);
for i = 1:ncomp
    for j = 1:ncomp
        if (strcmpi(na{i}, 'Water') && strcmpi(na{j}, 'CarbonDioxide')) ...
                || (strcmpi(na{j}, 'Water') && strcmpi(na{i}, 'CarbonDioxide'))
            bic(i,j) = -0.515*(T/304.1282)^2+1.65215*(T/304.1282)-1.04175;
        elseif (strcmpi(na{i}, 'Water') && strcmpi(na{j}, 'HydrogenSulfide')) ...
                || (strcmpi(na{j}, 'Water') && strcmpi(na{i}, 'HydrogenSulfide'))
            bic(i,j) = -0.379876*(T/373.1)^2+0.873717*(T/373.1)-0.311971;
        elseif (strcmpi(na{i}, 'Water') && strcmpi(na{j}, 'Nitrogen')) ...
                || (strcmpi(na{j}, 'Water') && strcmpi(na{i}, 'Nitrogen'))
            bic(i,j) = 0.0578675*(T/126.192)^4-0.844736*(T/126.192)^3+4.2075455*(T/126.192)^2-8.30813*(T/126.192)+5.275865;
        elseif (strcmpi(na{i}, 'Water') && strcmpi(na{j}, 'Oxygen')) ...
                || (strcmpi(na{j}, 'Water') && strcmpi(na{i}, 'Oxygen'))
            bic(i,j) = 0.0896695*(T/154.581)^3-0.928507*(T/154.581)^2+3.2950445*(T/154.581)-3.471575;
        elseif (strcmpi(na{i}, 'Water') && strcmpi(na{j}, 'Argon')) ...
                || (strcmpi(na{j}, 'Water') && strcmpi(na{i}, 'Argon'))
            bic(i,j) = 0.0977033*(T/150.687)^3-0.96074999*(T/150.687)^2+3.3311513*(T/150.687)-3.550028;
        elseif (strcmpi(na{i}, 'Water') && strcmpi(na{j}, 'SulfurDioxide')) ...
                || (strcmpi(na{j}, 'Water') && strcmpi(na{i}, 'SulfurDioxide'))
            bic(i,j) = -0.2553*(T/430.64)+0.0672;
        elseif (strcmpi(na{i}, 'Water') && strcmpi(na{j}, 'Methane')) ...
                || (strcmpi(na{j}, 'Water') && strcmpi(na{i}, 'Methane'))
            bic(i,j) = -0.364714*(T/190.564)^2+1.73109*(T/190.564)-1.817027;
        elseif (strcmpi(na{i}, 'Water') && strcmpi(na{j}, 'Ethane')) ...
                || (strcmpi(na{j}, 'Water') && strcmpi(na{i}, 'Ethane'))
            bic(i,j) = -0.78621*(T/305.322)^2+2.23196*(T/305.322)-1.38006;
        elseif (strcmpi(na{i}, 'Water') && strcmpi(na{j}, 'n-Propane')) ...
                || (strcmpi(na{j}, 'Water') && strcmpi(na{i}, 'n-Propane'))
            bic(i,j) = -0.79876*(T/369.89)^2+1.85127*(T/369.89)-0.92172;
        elseif (strcmpi(na{i}, 'CarbonDioxide') && strcmpi(na{j}, 'HydrogenSulfide')) ...
                || (strcmpi(na{j}, 'CarbonDioxide') && strcmpi(na{i}, 'HydrogenSulfide'))
            bic(i,j) = 0.1;
        elseif (strcmpi(na{i}, 'CarbonDioxide') && strcmpi(na{j}, 'Nitrogen')) ...
                || (strcmpi(na{j}, 'CarbonDioxide') && strcmpi(na{i}, 'Nitrogen'))
            bic(i,j) = -0.0712;
        elseif (strcmpi(na{i}, 'CarbonDioxide') && strcmpi(na{j}, 'Oxygen')) ...
                || (strcmpi(na{j}, 'CarbonDioxide') && strcmpi(na{i}, 'Oxygen'))
            bic(i,j) = 0.0770;
        elseif (strcmpi(na{i}, 'CarbonDioxide') && strcmpi(na{j}, 'Argon')) ...
                || (strcmpi(na{j}, 'CarbonDioxide') && strcmpi(na{i}, 'Argon'))
            bic(i,j) = 0.089;
        elseif (strcmpi(na{i}, 'CarbonDioxide') && strcmpi(na{j}, 'SulfurDioxide')) ...
                || (strcmpi(na{j}, 'CarbonDioxide') && strcmpi(na{i}, 'SulfurDioxide'))
            bic(i,j) = 0.029;
        elseif (strcmpi(na{i}, 'CarbonDioxide') && strcmpi(na{j}, 'Methane')) ...
                || (strcmpi(na{j}, 'CarbonDioxide') && strcmpi(na{i}, 'Methane'))
            bic(i,j) = 0.1;
        elseif (strcmpi(na{i}, 'CarbonDioxide') && strcmpi(na{j}, 'Ethane')) ...
                || (strcmpi(na{j}, 'CarbonDioxide') && strcmpi(na{i}, 'Ethane'))
            bic(i,j) = 0.138;
        elseif (strcmpi(na{i}, 'CarbonDioxide') && strcmpi(na{j}, 'n-Propane')) ...
                || (strcmpi(na{j}, 'CarbonDioxide') && strcmpi(na{i}, 'n-Propane'))
            bic(i,j) = 0.126;
        elseif (strcmpi(na{i}, 'HydrogenSulfide') && strcmpi(na{j}, 'Nitrogen')) ...
                || (strcmpi(na{j}, 'HydrogenSulfide') && strcmpi(na{i}, 'Nitrogen'))
            bic(i,j) = 0.1499;
        elseif (strcmpi(na{i}, 'HydrogenSulfide') && strcmpi(na{j}, 'Oxygen')) ...
                || (strcmpi(na{j}, 'HydrogenSulfide') && strcmpi(na{i}, 'Oxygen'))
            bic(i,j) = 0;
        elseif (strcmpi(na{i}, 'HydrogenSulfide') && strcmpi(na{j}, 'Argon')) ...
                || (strcmpi(na{j}, 'HydrogenSulfide') && strcmpi(na{i}, 'Argon'))
            bic(i,j) = 0;
        elseif (strcmpi(na{i}, 'HydrogenSulfide') && strcmpi(na{j}, 'SulfurDioxide')) ...
                || (strcmpi(na{j}, 'HydrogenSulfide') && strcmpi(na{i}, 'SulfurDioxide'))
            bic(i,j) = 0;
        elseif (strcmpi(na{i}, 'HydrogenSulfide') && strcmpi(na{j}, 'Methane')) ...
                || (strcmpi(na{j}, 'HydrogenSulfide') && strcmpi(na{i}, 'Methane'))
            bic(i,j) = 0.0852;
        elseif (strcmpi(na{i}, 'HydrogenSulfide') && strcmpi(na{j}, 'Ethane')) ...
                || (strcmpi(na{j}, 'HydrogenSulfide') && strcmpi(na{i}, 'Ethane'))
            bic(i,j) = 0.086;
        elseif (strcmpi(na{i}, 'HydrogenSulfide') && strcmpi(na{j}, 'n-Propane')) ...
                || (strcmpi(na{j}, 'HydrogenSulfide') && strcmpi(na{i}, 'n-Propane'))
            bic(i,j) = 0.109;
        elseif (strcmpi(na{i}, 'Nitrogen') && strcmpi(na{j}, 'Oxygen')) ...
                || (strcmpi(na{j}, 'Nitrogen') && strcmpi(na{i}, 'Oxygen'))
            bic(i,j) = -0.028;
        elseif (strcmpi(na{i}, 'Nitrogen') && strcmpi(na{j}, 'Argon')) ...
                || (strcmpi(na{j}, 'Nitrogen') && strcmpi(na{i}, 'Argon'))
            bic(i,j) = -0.005;
        elseif (strcmpi(na{i}, 'Nitrogen') && strcmpi(na{j}, 'SulfurDioxide')) ...
                || (strcmpi(na{j}, 'Nitrogen') && strcmpi(na{i}, 'SulfurDioxide'))
            bic(i,j) = -0.056;
        elseif (strcmpi(na{i}, 'Nitrogen') && strcmpi(na{j}, 'Methane')) ...
                || (strcmpi(na{j}, 'Nitrogen') && strcmpi(na{i}, 'Methane'))
            bic(i,j) = 0.0393;
        elseif (strcmpi(na{i}, 'Nitrogen') && strcmpi(na{j}, 'Ethane')) ...
                || (strcmpi(na{j}, 'Nitrogen') && strcmpi(na{i}, 'Ethane'))
            bic(i,j) = 0.03;
        elseif (strcmpi(na{i}, 'Nitrogen') && strcmpi(na{j}, 'n-Propane')) ...
                || (strcmpi(na{j}, 'Nitrogen') && strcmpi(na{i}, 'n-Propane'))
            bic(i,j) = 0.029;
        elseif (strcmpi(na{i}, 'Oxygen') && strcmpi(na{j}, 'Argon')) ...
                || (strcmpi(na{j}, 'Oxygen') && strcmpi(na{i}, 'Argon'))
            bic(i,j) = 0.0080;
        elseif (strcmpi(na{i}, 'Oxygen') && strcmpi(na{j}, 'SulfurDioxide')) ...
                || (strcmpi(na{j}, 'Oxygen') && strcmpi(na{i}, 'SulfurDioxide'))
            bic(i,j) = 0.0990;
        elseif (strcmpi(na{i}, 'Oxygen') && strcmpi(na{j}, 'Methane')) ...
                || (strcmpi(na{j}, 'Oxygen') && strcmpi(na{i}, 'Methane'))
            bic(i,j) = 0;
        elseif (strcmpi(na{i}, 'Oxygen') && strcmpi(na{j}, 'Ethane')) ...
                || (strcmpi(na{j}, 'Oxygen') && strcmpi(na{i}, 'Ethane'))
            bic(i,j) = 0;
        elseif (strcmpi(na{i}, 'Oxygen') && strcmpi(na{j}, 'n-Propane')) ...
                || (strcmpi(na{j}, 'Oxygen') && strcmpi(na{i}, 'n-Propane'))
            bic(i,j) = 0.1080;
        elseif (strcmpi(na{i}, 'Argon') && strcmpi(na{j}, 'SulfurDioxide')) ...
                || (strcmpi(na{j}, 'Argon') && strcmpi(na{i}, 'SulfurDioxide'))
            bic(i,j) = 0.0860;
        elseif (strcmpi(na{i}, 'Argon') && strcmpi(na{j}, 'Methane')) ...
                || (strcmpi(na{j}, 'Argon') && strcmpi(na{i}, 'Methane'))
            bic(i,j) = 0.0110;
        elseif (strcmpi(na{i}, 'Argon') && strcmpi(na{j}, 'Ethane')) ...
                || (strcmpi(na{j}, 'Argon') && strcmpi(na{i}, 'Ethane'))
            bic(i,j) = 0;
        elseif (strcmpi(na{i}, 'Argon') && strcmpi(na{j}, 'n-Propane')) ...
                || (strcmpi(na{j}, 'Argon') && strcmpi(na{i}, 'n-Propane'))
            bic(i,j) = 0;
        elseif (strcmpi(na{i}, 'SulfurDioxide') && strcmpi(na{j}, 'Methane')) ...
                || (strcmpi(na{j}, 'SulfurDioxide') && strcmpi(na{i}, 'Methane'))
            bic(i,j) = 0.0470;
        elseif (strcmpi(na{i}, 'SulfurDioxide') && strcmpi(na{j}, 'Ethane')) ...
                || (strcmpi(na{j}, 'SulfurDioxide') && strcmpi(na{i}, 'Ethane'))
            bic(i,j) = 0;
        elseif (strcmpi(na{i}, 'SulfurDioxide') && strcmpi(na{j}, 'n-Propane')) ...
                || (strcmpi(na{j}, 'SulfurDioxide') && strcmpi(na{i}, 'n-Propane'))
            bic(i,j) = 0;
        elseif (strcmpi(na{i}, 'Methane') && strcmpi(na{j}, 'Ethane')) ...
                || (strcmpi(na{j}, 'Methane') && strcmpi(na{i}, 'Ethane'))
            bic(i,j) = 0.0070;
        elseif (strcmpi(na{i}, 'Methane') && strcmpi(na{j}, 'n-Propane')) ...
                || (strcmpi(na{j}, 'Methane') && strcmpi(na{i}, 'n-Propane'))
            bic(i,j) = 0.0110;
        elseif (strcmpi(na{i}, 'Ethane') && strcmpi(na{j}, 'n-Propane')) ...
                || (strcmpi(na{j}, 'Ethane') && strcmpi(na{i}, 'n-Propane'))
            bic(i,j) = 0.0220;
        end
    end
end
end
