function varargout = implicitupwind_mex(varargin)

   % Build MEX edition of same.
   %
   v = version;v = v([1,3]);
   d = fileparts(mfilename('fullpath'));
   CFLAGS = {'CFLAGS="\$CFLAGS', '-O3', '-Wall', '-Wextra', '-ansi', ...
             '-pedantic', '-Wformat-nonliteral',  '-Wcast-align', ...
             '-Wpointer-arith', '-Wbad-function-cast', ...
             '-Wmissing-prototypes ', '-Wstrict-prototypes', ...
             '-Wmissing-declarations', '-Winline', '-Wundef', ...
             '-Wnested-externs', '-Wcast-qual', '-Wshadow', ...
             '-Wconversion', '-Wwrite-strings', '-Wno-conversion', ...
             '-Wchar-subscripts', '-Wredundant-decls"'};

   SRC = {'implicitupwind_mex.c', 'twophasetransport.c', 'nlsolvers.c', ...
          'reordersequence.c', 'tarjan.c', 'twophase.c', 'fluid.c',...
          fullfile(d, '..','..', 'mrst_api', 'mrst_api.c'),};

   INCLUDE = { ['-I', fullfile(d, '..','..', 'mrst_api')] };

   OPTS = {'-output', ['implicitupwind_mex.', mexext], ...
      '-largeArrayDims', ['-DMATLABVERSION=', v], '-O'};

   buildmex(CFLAGS{:}, INCLUDE{:}, OPTS{:}, SRC{:})

   % Call MEX edition.
   [varargout{1:nargout}] = implicitupwind_mex(varargin{:});
end
