function varargout = mex_opmcoreTransportReorder(varargin)
   d = fileparts(mfilename('fullpath'));

   CFLAGS = {'CFLAGS="\$CFLAGS', '-Wall', '-Wextra', '-ansi', ...
             '-pedantic', '-Wformat-nonliteral',  '-Wcast-align', ...
             '-Wpointer-arith', '-Wbad-function-cast', ...
             '-Wmissing-prototypes ', '-Wstrict-prototypes', ...
             '-Wmissing-declarations', '-Winline', '-Wundef', ...
             '-Wnested-externs', '-Wcast-qual', '-Wshadow', ...
             '-Wconversion', '-Wwrite-strings', '-Wno-conversion', ...
             '-Wchar-subscripts', '-Wredundant-decls"'};

   LDFLAGS = { };
   INCLUDE = { '-I/usr/local/include' };

   LINK = { '-L/usr/local/lib' };

   OPTS = { '-O', '-largeArrayDims' };

   SRC = { 'mex_opmcoreTransportReorder.cpp', ...
           fullfile(d, '..', 'mrst_api', 'mrst_api.c') };

   LIBS = { '-lopmcore', '-lboost_filesystem', '-lboost_system', ...
            '-lmwblas', '-lmwlapack', '-lecl' };

   buildmex(CFLAGS{:}, LDFLAGS{:}, ...
            INCLUDE{:}, LINK{:}, OPTS{:}, SRC{:}, LIBS{:});

   % Call MEX'ed edition.
   [varargout{1:nargout}] = mex_opmcoreTransportReorder(varargin{:});
end
