function [ fluid ] = reconstructFluidStructure( Gt, rock2D, opt, dh )
% Reconstruct the fluid structure using parameters defined in opt.

    % This avoids the requirement of saving each fluid structure along with
    % the optimization results of a given formation case.

    % Note: we assume that dh is empty, because either no subtrap file was
    % specified or located. Consequently, opt.surf_topo should have been
    % set to 'smooth'.
    assert(isempty(dh));
    assert(strcmpi(opt.surf_topo,'smooth'));
    
    % Need to test this function when a subtrap file was used, i.e., dh is
    % not empty @@
    
    % if opt.dissolution does not exist, set it equal to false
    if ~isfield(opt,'dissolution')
        opt.dissolution = false;
    end

   % computing fixed temperature field
   T_ref = opt.ref_temp + opt.temp_grad * (Gt.cells.z - opt.ref_depth) / 1000;   
              
   fluid = makeVEFluid(Gt, rock2D, 'sharp interface'                   , ...
                       'fixedT'       , T_ref                          , ...
                       'residual'     , [opt.sw        , opt.sr]       , ...
                       'wat_rho_ref'  , opt.rhoW                       , ...
                       'co2_rho_ref'  , opt.refRhoCO2                  , ... 
                       'wat_rho_pvt'  , [opt.c_water   , opt.refPress] , ...
                       'co2_rho_pvt'  , [opt.p_range   , opt.t_range]  , ...
                       'wat_mu_ref'   , opt.muBrine                    , ...
                       'co2_mu_pvt'   , [opt.p_range   , opt.t_range]  , ...
                       'pvMult_fac'   , opt.pvMult                     , ...
                       'pvMult_p_ref' , opt.refPress                   , ...
                       'dissolution'  , opt.dissolution                , ...
                       'dis_rate'     , opt.dis_rate                   , ...
                       'dis_max'      , opt.dis_max                    , ...
                       'surf_topo'    , opt.surf_topo                  , ...
                       'top_trap'     , dh);


end

