function setup = packTestCaseSetup(name, varargin)
    setup = struct('name'       , name, ...
                   'description', []  , ...
                   'options'    , []  , ...
                   'state0'     , []  , ...
                   'model'      , []  , ...
                   'schedule'   , []  , ...
                   'plotOptions', {{}});
    setup = merge_options(setup, varargin{:});
end