function state = solveIncompFlow(varargin)
% Deprecated function - use incompMimetic instead.
    warning('mrst:solveIncompFlow', ...
            ['the ''solveIncompFlow'' function is deprecated and will be removed', ...
             'in an upcoming release of MRST. Use the functionally identical', ...
             '''incompMimetic'' instead.']);
    state = incompMimetic(varargin{:});
end