function region = getInitializationRegionsBase(model, cells, reference_ix, rho, datum_p, datum_z, contacts, varargin)
    nph = sum(model.getActivePhases());
    
    assert(numel(contacts) == nph-1);
    assert(isscalar(datum_z));
    assert(isscalar(datum_p));
    
    region = struct('datum_pressure',  datum_p, ...
                    'datum_depth',     datum_z, ...
                    'reference_index', reference_ix, ...
                    'cells',           cells, ...
                    'rho',             {rho}, ...
                    'contacts',        contacts, ...
                    'pc_sign',         ones(1, nph), ...
                    'pc_functions',    {{}}, ...
                    'contacts_pc',     zeros(1, nph), ...
                    's_max',           ones(1, nph), ...
                    's_min',           zeros(1, nph) ...
                );
    region = merge_options(region, varargin{:});
    
    assert(numel(region.contacts_pc) == numel(contacts));

end