%% Figure 1-3

% These figures are not generated by Matlab

%% Figure 4

% Left pane:
showAquiferModel;

% Right pane:
showDensityVariation;

%% Figure 5 and 6

runStandardModel('data/residualExample1Data', @plotResidualFigs , ...
                 'A'             , [0 2]                        , ...
                 'residual'      , [false true]                 , ...
                 'dis_types'     , {'none'});

%% Figure 7 and 8

clear all; firstPlioExample;

%% Figure 9

% This figure is not generated by Matlab

%% Figure 10
clear all; showUpscaledRelPerms;

%% Figure 11

% Left figure
runStandardModel('data/upscalingExample1Data', @plotUpscalingFigs             , ...
                 'A', [2]                                                     , ...
                 'subscale_types', {'smooth', 'inf_rough', 'square', 'sinus'} , ...
                 'residual', true                                             , ...
                 'dis_types', {'none'});

% Right figure
showUpscaledRelPerms;

%% Figure 12, 13 and 14

runStandardModel('data/dissolutionExample1Data', @plotDissolutionFigs , ...
                 'depth', 1300                                        , ...
                 'residual', [false true]                             , ...
                 'A', [0 2]                                           , ...
                 'dis_types', {'none', 'rate'});
                 
%% Figure 15

% This figure is not generated by Matlab

