function G = cartGridZShifted(celldim, physdim, exponent)

   G = cartGrid(celldim, physdim);

   shiftfun = @(x) physdim(3) * ((x/physdim(3)) .^ exponent);

   G.nodes.coords(:,3) = reshape(repmat(shiftfun(linspace(0, ...
                                                          physdim(3), ...
                                                          celldim(3) + 1)), ...
                                        size(G.nodes.coords, 1) / (celldim(3) + 1), ...
                                        1), ...
                                 [], ...
                                 1);
end
