function [problem, state] = equationsMICP( ...
        state0, state, model, dt, drivingForces, varargin)
% Assemble the linearized equations for the MICP system.
%
% This function is modified from a file in the MATLAB Reservoir Simulation
% Toolbox (MRST), see
%   mrst/modules/ad-eor/utils/equationsOilWaterPolymer.m
%
% We refer to that function for a complete commented version of the file.
% In this file, we comment on the newly added lines.

%{
Partial copyright 2009-2021, SINTEF Digital, Mathematics & Cybernetics.
Partial copyright 2021-2026, NORCE Research AS, Computational Geosciences and
Modeling.

This file is part of the ad-micp module.

ad-micp is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

ad-micp is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this file. If not, see <http://www.gnu.org/licenses/>.
%}
    options = struct( ...
        'Verbose', mrstVerbose, ...
        'reverseMode', false, ...
        'resOnly', false, ...
        'iteration', -1);

    options = merge_options(options, varargin{:});

    fluid = model.fluid;
    grid = model.G;

    % Model parameters
    cellTemplate = ones(grid.cells.num, 1);
    waterDensity = fluid.rhoWS .* cellTemplate;
    waterMobility = cellTemplate ./ fluid.muw;
    biofilmDensity = fluid.rho_b;
    calciteDensity = fluid.rho_c;
    detachmentRate = fluid.k_str;
    ureaUtilizationRate = fluid.mu_u;
    attachmentRate = fluid.k_a;
    deathRate = fluid.k_d;
    oxygenHalfVelocity = fluid.k_o;
    ureaHalfVelocity = fluid.k_u;
    calciteYield = fluid.Yuc;
    maximumGrowthRate = fluid.mu;
    growthYield = fluid.Y;
    oxygenConsumptionFactor = fluid.F;

    % Properties at the current timestep
    [pressure, waterSaturation, microorganism, oxygen, urea, ...
        biofilm, calcite, wellSol] = ...
        model.getProps( ...
        state, ...
        'pressure', ...
        'water', ...
        'microorganism', ...
        'oxygen', ...
        'urea', ...
        'biofilm', ...
        'calcite', ...
        'wellSol');

    % Properties at the previous timestep
    [waterSaturation0, microorganism0, oxygen0, urea0, ...
        biofilm0, calcite0, wellSol0] = ...
        model.getProps( ...
        state0, ...
        'water', ...
        'microorganism', ...
        'oxygen', ...
        'urea', ...
        'biofilm', ...
        'calcite', ...
        'wellSol');

    [wellVariables, wellVariableNames, wellMap] = ...
        model.FacilityModel.getAllPrimaryVariables(wellSol);

    micpPrimaryVariables = { ...
        'pressure', ...
        'sW', ...
        'microorganism', ...
        'oxygen', ...
        'urea', ...
        'biofilm', ...
        'calcite'};

    % Initialize independent variables
    if options.resOnly
        primaryVariables = micpPrimaryVariables;
    elseif options.reverseMode
        [waterSaturation0, microorganism0, oxygen0, urea0, ...
            biofilm0, calcite0] = ...
            initVariablesADI( ...
            waterSaturation0, ...
            microorganism0, ...
            oxygen0, ...
            urea0, ...
            biofilm0, ...
            calcite0);

        primaryVariables = micpPrimaryVariables;
    else
        [pressure, waterSaturation, microorganism, oxygen, urea, ...
            biofilm, calcite, wellVariables{:}] = ...
            initVariablesADI( ...
            pressure, ...
            waterSaturation, ...
            microorganism, ...
            oxygen, ...
            urea, ...
            biofilm, ...
            calcite, ...
            wellVariables{:});

        primaryVariables = [ ...
            micpPrimaryVariables, ...
            wellVariableNames(:)'];
    end

    % Single-phase flow (sW = 1, sO = 0), with the possibility of
    % extending the implementation to two-phase flow.
    oilSaturation = 1 - waterSaturation;
    gravityGradient = model.getGravityGradient();

    referencePorosity = model.referencePorosity;
    minimumPorosity = model.minimumPorosity;
    maximumSolidVolume = ...
        referencePorosity - minimumPorosity;

    porosity0 = referencePorosity - biofilm0 - calcite0;
    porosity0 = max(porosity0, minimumPorosity);

    porosity = referencePorosity - biofilm - calcite;
    porosity = max(porosity, minimumPorosity);

    % MRST rock and transmissibility utilities require numeric porosity.
    % The AD porosity is retained in the accumulation and reaction terms.
    numericPorosity = value(porosity);

    [waterFlux, microorganismFlux, oxygenFlux, ureaFlux, model] = ...
        getFluxAndPropsMICP( ...
        model, ...
        pressure, ...
        microorganism, ...
        oxygen, ...
        urea, ...
        gravityGradient, ...
        numericPorosity);

    state = model.storeFluxes( ...
        state, waterFlux, 0 .* waterFlux, []);

    [microorganismDispersion, oxygenDispersion, ureaDispersion, ...
        pressureGradientMagnitude] = ...
        getDispersionAnddpWMICP( ...
        model, state, numericPorosity);

    operators = model.operators;
    cellVolumes = grid.cells.volumes;

    % Common accumulation and reaction terms
    accumulationScale = cellVolumes ./ dt;
    inverseTimeStep = 1 ./ dt;

    oxygenMonodFactor = ...
        oxygen ./ (oxygenHalfVelocity + oxygen);

    ureaMonodFactor = ...
        urea ./ (ureaHalfVelocity + urea);

    specificGrowthRate = ...
        maximumGrowthRate .* oxygenMonodFactor;

    specificUreaUtilization = ...
        ureaUtilizationRate .* ureaMonodFactor;

    shearFactor = ...
        (porosity .* pressureGradientMagnitude) .^ 0.58;

    specificDetachmentRate = ...
        detachmentRate .* shearFactor;

    unconstrainedCalciteProductionRate = ...
        biofilmDensity .* biofilm .* calciteYield .* ...
        specificUreaUtilization ./ calciteDensity;

    % Limit positive solid formation to the pore volume available at the
    % current nonlinear state. Death and detachment remain active, but pore
    % volume released by them is available to formation in later updates.
    availableSolidVolume = max( ...
        maximumSolidVolume - biofilm - calcite, 0);

    biofilmGrowthVolumeRate = ...
        biofilm .* growthYield .* specificGrowthRate;

    attachmentVolumeRate = ...
        microorganism .* porosity .* ...
        attachmentRate ./ biofilmDensity;

    positiveSolidFormationRate = ...
        biofilmGrowthVolumeRate + ...
        attachmentVolumeRate + ...
        unconstrainedCalciteProductionRate;

    solidFormationOverTimeStep = ...
        dt .* positiveSolidFormationRate;

    solidFormationLimiter = min( ...
        1, ...
        availableSolidVolume ./ ...
        max(solidFormationOverTimeStep, minimumPorosity));

    limitedAttachmentRate = ...
        solidFormationLimiter .* attachmentRate;

    limitedBiofilmGrowthRate = ...
        solidFormationLimiter .* ...
        growthYield .* specificGrowthRate;

    limitedSpecificUreaUtilization = ...
        solidFormationLimiter .* ...
        specificUreaUtilization;

    calciteProductionRate = ...
        biofilmDensity .* biofilm .* calciteYield .* ...
        limitedSpecificUreaUtilization ./ calciteDensity;
    
    biofilmCalciteDenominator = max( ...
        porosity + biofilm, minimumPorosity);

    % Conservation of mass for water
    waterEquation = ...
        accumulationScale .* ...
        (porosity .* waterSaturation - ...
        porosity0 .* waterSaturation0) + ...
        operators.Div(waterFlux);

    % Conservation of mass for oil/CO2. This saturation constraint
    % enforces single-phase water flow and may be extended to two phases.
    oilEquation = oilSaturation;

    % Conservation of mass for microorganisms
    microorganismEquation = ...
        accumulationScale .* ...
        (porosity .* microorganism - ...
        porosity0 .* microorganism0) + ...
        operators.Div( ...
        microorganismFlux - ...
        microorganismDispersion .* ...
        operators.Grad(microorganism)) - ...
        cellVolumes .* ( ...
        microorganism .* porosity .* ...
        (growthYield .* specificGrowthRate - ...
        deathRate - limitedAttachmentRate) + ...
        biofilm .* biofilmDensity .* specificDetachmentRate);

    % Conservation of mass for oxygen
    oxygenEquation = ...
        accumulationScale .* ...
        (porosity .* oxygen - porosity0 .* oxygen0) + ...
        operators.Div( ...
        oxygenFlux - ...
        oxygenDispersion .* operators.Grad(oxygen)) + ...
        cellVolumes .* oxygenConsumptionFactor .* ( ...
        microorganism .* porosity .* specificGrowthRate + ...
        biofilmDensity .* biofilm .* ...
        solidFormationLimiter .* specificGrowthRate);

    % Conservation of mass for urea
    ureaEquation = ...
        accumulationScale .* ...
        (porosity .* urea - porosity0 .* urea0) + ...
        operators.Div( ...
        ureaFlux - ...
        ureaDispersion .* operators.Grad(urea)) + ...
        cellVolumes .* biofilmDensity .* biofilm .* ...
        limitedSpecificUreaUtilization;

    % Conservation of mass for biofilm
    biofilmEquation = ...
        inverseTimeStep .* (biofilm - biofilm0) - ...
        biofilm .* ( ...
        limitedBiofilmGrowthRate - ...
        deathRate - ...
        calciteProductionRate ./ biofilmCalciteDenominator - ...
        specificDetachmentRate) - ...
        microorganism .* porosity .* ...
        limitedAttachmentRate ./ biofilmDensity;

    % Conservation of mass for calcite
    calciteEquation = ...
        inverseTimeStep .* (calcite - calcite0) - ...
        calciteProductionRate;

    equationNames = { ...
        'water', ...
        'oil', ...
        'microorganism', ...
        'oxygen', ...
        'urea', ...
        'biofilm', ...
        'calcite'};

    equations = { ...
        waterEquation, ...
        oilEquation, ...
        microorganismEquation, ...
        oxygenEquation, ...
        ureaEquation, ...
        biofilmEquation, ...
        calciteEquation};

    equationTypes = repmat({'cell'}, size(equations));

    micpComponents = { ...
        microorganism, ...
        oxygen, ...
        urea, ...
        biofilm, ...
        calcite};

    phasePressures = { ...
        pressure, ...
        pressure};

    phaseSaturations = { ...
        waterSaturation, ...
        oilSaturation};

    phaseMobilities = { ...
        waterMobility, ...
        0 .* waterMobility};

    phaseDensities = { ...
        waterDensity, ...
        waterDensity};

    dissolvedGasRatios = {};

    [equations, state] = addBoundaryConditionsAndSources( ...
        model, ...
        equations, ...
        equationNames, ...
        equationTypes, ...
        state, ...
        phasePressures, ...
        phaseSaturations, ...
        phaseMobilities, ...
        phaseDensities, ...
        dissolvedGasRatios, ...
        micpComponents, ...
        drivingForces);

    [equations, equationNames, equationTypes, state.wellSol] = ...
        model.insertWellEquations( ...
        equations, ...
        equationNames, ...
        equationTypes, ...
        wellSol0, ...
        wellSol, ...
        wellVariables, ...
        wellMap, ...
        pressure, ...
        phaseMobilities, ...
        phaseDensities, ...
        dissolvedGasRatios, ...
        micpComponents, ...
        dt, ...
        options);

    problem = LinearizedProblem( ...
        equations, ...
        equationTypes, ...
        equationNames, ...
        primaryVariables, ...
        state, ...
        dt);
end
