function fn = getPlotAfterStepMICP(state0, model, az, el)
% Get a function that allows for dynamic plotting in `simulateScheduleAD`
% for the MICP model. The parameters az and el are the azimuth and
% elevation angles for the current axes.
%
% This function is modified from a file in the MATLAB Reservoir Simulation
% Toolbox (MRST), see
%   mrst/modules/solvent/utils/getPlotAfterStepSolvent.m
%
% We refer to that function for a complete commented version of the file.
% In this file, we comment on some of the lines.

%{
Partial copyright 2009-2021, SINTEF Digital, Mathematics & Cybernetics.
Partial copyright 2021-2026, NORCE Research AS, Computational Geosciences and
Modeling.

This file is part of the ad-micp module.

ad-micp is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

ad-micp is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this file. If not, see <http://www.gnu.org/licenses/>.
%}
    grid = model.G;
    defaultFigurePosition = get(0, 'defaultFigurePosition');

    resultFigure = figure( ...
        'Position', [defaultFigurePosition(1 : 2), 800, 1200]);

    colorMap = flipud(jet);
    numberOfColors = size(colorMap, 1);

    microorganismAxes = subplot(3, 2, 1, ...
        'Parent', resultFigure);
    microorganismPlot = plotCellData( ...
        grid, state0.m, 'EdgeColor', 'none');
    title( ...
        microorganismAxes, ...
        'Microorganisms [kg/m$^3$]', ...
        'Interpreter', 'latex');
    colorbar(microorganismAxes);
    view(microorganismAxes, az, el);
    colormap( ...
        microorganismAxes, ...
        colorMap( ...
        round(70 * numberOfColors / 256) : ...
        round(120 * numberOfColors / 256), :));

    oxygenAxes = subplot(3, 2, 2, ...
        'Parent', resultFigure);
    oxygenPlot = plotCellData( ...
        grid, state0.o, 'EdgeColor', 'none');
    title( ...
        oxygenAxes, ...
        'Oxygen [kg/m$^3$]', ...
        'Interpreter', 'latex');
    colorbar(oxygenAxes);
    view(oxygenAxes, az, el);
    colormap( ...
        oxygenAxes, ...
        colorMap( ...
        round(70 * numberOfColors / 256) : ...
        round(180 * numberOfColors / 256), :));
    caxis(oxygenAxes, [0 model.fluid.Comax]);

    biofilmAxes = subplot(3, 2, 3, ...
        'Parent', resultFigure);
    biofilmPlot = plotCellData( ...
        grid, state0.b, 'EdgeColor', 'none');
    title( ...
        biofilmAxes, ...
        'Biofilm [-]', ...
        'Interpreter', 'latex');
    colorbar(biofilmAxes);
    view(biofilmAxes, az, el);
    colormap( ...
        biofilmAxes, ...
        colorMap( ...
        round(70 * numberOfColors / 256) : ...
        round(120 * numberOfColors / 256), :));
    caxis(biofilmAxes, ...
        [0 max(model.referencePorosity(:))]);

    ureaAxes = subplot(3, 2, 4, ...
        'Parent', resultFigure);
    ureaPlot = plotCellData( ...
        grid, state0.u, 'EdgeColor', 'none');
    title( ...
        ureaAxes, ...
        'Urea [kg/m$^3$]', ...
        'Interpreter', 'latex');
    colorbar(ureaAxes);
    view(ureaAxes, az, el);
    colormap( ...
        ureaAxes, ...
        colorMap( ...
        round(70 * numberOfColors / 256) : ...
        round(100 * numberOfColors / 256), :));
    caxis(ureaAxes, [0 model.fluid.Cumax]);

    calciteAxes = subplot(3, 2, 5, ...
        'Parent', resultFigure);
    calcitePlot = plotCellData( ...
        grid, state0.c, 'EdgeColor', 'none');
    title( ...
        calciteAxes, ...
        'Calcite [-]', ...
        'Interpreter', 'latex');
    colorbar(calciteAxes);
    view(calciteAxes, az, el);
    colormap( ...
        calciteAxes, ...
        colorMap( ...
        round(70 * numberOfColors / 256) : end, :));
    caxis(calciteAxes, ...
        [0 max(model.referencePorosity(:))]);

    permeabilityAxes = subplot(3, 2, 6, ...
        'Parent', resultFigure);

    initialPorosity = max( ...
        model.referencePorosity - state0.b - state0.c, ...
        model.minimumPorosity);

    referencePermeability = ...
        model.fluid.K(model.referencePorosity);
    referencePermeability = max( ...
        referencePermeability, model.fluid.kmin);

    initialPermeability = ...
        model.fluid.K(initialPorosity);
    initialPermeability = max( ...
        initialPermeability, model.fluid.kmin);

    permeabilityReduction = 100 .* ( ...
        1 - initialPermeability ./ referencePermeability);

    permeabilityReduction = min( ...
        max(permeabilityReduction, 0), 100);

    permeabilityPlot = plotCellData( ...
        grid, permeabilityReduction, 'EdgeColor', 'none');
    title( ...
        permeabilityAxes, ...
        'Permeability reduction [\%]', ...
        'Interpreter', 'latex');
    colorbar(permeabilityAxes);
    view(permeabilityAxes, az, el);
    colormap( ...
        permeabilityAxes, ...
        colorMap( ...
        round(70 * numberOfColors / 256) : end, :));
    caxis(permeabilityAxes, [0 100]);

    fn = @(model, states, reports, solver, schedule, simtime) ...
        afterStepFunction( ...
        model, states, reports, solver, schedule, simtime, ...
        resultFigure, microorganismPlot, oxygenPlot, ...
        biofilmPlot, ureaPlot, calcitePlot, ...
        permeabilityPlot);
end

function [model, states, reports, solver, ok] = afterStepFunction( ...
        model, states, reports, solver, schedule, simtime, ...
        resultFigure, microorganismPlot, oxygenPlot, ...
        biofilmPlot, ureaPlot, calcitePlot, ...
        permeabilityPlot)

    computedStates = cellfun( ...
        @(state) ~isempty(state), states);

    computedReports = cellfun( ...
        @(report) ~isempty(report), reports);

    currentStateIndex = find( ...
        computedStates, 1, 'last');

    if isempty(currentStateIndex)
        ok = true;
        return
    end

    currentState = states{currentStateIndex};
    completedSimulationTime = simtime(computedReports);

    [~, boundaryCells] = boundaryFaces(model.G);

    graphicsObjects = [ ...
        microorganismPlot, ...
        oxygenPlot, ...
        biofilmPlot, ...
        ureaPlot, ...
        calcitePlot, ...
        permeabilityPlot];

    figureIsValid = ishandle(resultFigure);
    graphicsAreValid = all(ishandle(graphicsObjects));

    if figureIsValid && graphicsAreValid
        set(0, 'CurrentFigure', resultFigure);

        microorganismPlot.CData = ...
            currentState.m(boundaryCells, 1);

        oxygenPlot.CData = ...
            currentState.o(boundaryCells, 1);

        biofilmPlot.CData = ...
            currentState.b(boundaryCells, 1);

        ureaPlot.CData = ...
            currentState.u(boundaryCells, 1);

        calcitePlot.CData = ...
            currentState.c(boundaryCells, 1);

        currentPorosity = max( ...
            model.referencePorosity - ...
            currentState.b - currentState.c, ...
            model.minimumPorosity);

        currentPermeability = ...
            model.fluid.K(currentPorosity);
        currentPermeability = max( ...
            currentPermeability, model.fluid.kmin);

        referencePermeability = ...
            model.fluid.K(model.referencePorosity);
        referencePermeability = max( ...
            referencePermeability, model.fluid.kmin);

        permeabilityReduction = 100 .* ( ...
            1 - currentPermeability ./ referencePermeability);

        permeabilityReduction = min( ...
            max(permeabilityReduction, 0), 100);

        permeabilityPlot.CData = ...
            permeabilityReduction(boundaryCells, 1);

        drawnow;
    end

    ok = simulationRuntimePanel( ...
        model, states, reports, solver, schedule, ...
        completedSimulationTime);
end
