%% Figure 1-5

% These figures are not generated by Matlab

%% Figure 6

plotVEReconstruction(6);

%% Figure 7, 9 and 10

plotVEProfilesAndRelperms;

%% Figure 8

plotVEReconstruction(8);

%% Figure 11 and 12

dissolutionExampleCOMG2;

