NOECHO
-- Surfactant properties

SURFST
-- Concentration   Surface Tension
0    0.05
0.1  0.0005
0.5  1e-5
1    1e-6
30   1e-6
100  1e-6 /

SURFCAPD
-- capillary number interpolant
-10  0
-5.5 0
-4   0.5
-3   1
2    1   /
-10  0
-5.5 0
-4   0.5
-3   1
2    1   /

SURFVISC
-- Concentration   Viscosity mutliplier
0    0.48
0.5  1.44
1    2.4 /

SURFADS
-- Concentration Adsorption coefficient
0   0.
1   0.005
30  0.005
100 0.005 /
0   0.
1   0.005
30  0.005
100 0.005 /

SURFROCK
--AI Density
  1    2000 /
  1    2000 /


ECHO
