name: Run ad-micp

on:
 pull_request:
   
jobs:
  run-ad-micp-local:
    permissions:
      contents: read
    timeout-minutes: 20        
    runs-on: macos-26
    env:
      HOMEBREW_NO_REQUIRE_TAP_TRUST: "1"

    steps:
    - uses: actions/checkout@v5

    - name: Install octave
      run: |
        brew install octave
    
    - name: Download MRST, DistMesh, and install PR version
      run: |
        git clone --single-branch --depth 1 https://github.com/SINTEF-AppliedCompSci/MRST.git

        rm -rf MRST/modules/ad-micp
        mkdir -p MRST/modules/ad-micp

        # Copy the repository checked out from the PR
        rsync -a \
          --exclude='.git/' \
          --exclude='MRST/' \
          "$GITHUB_WORKSPACE/" \
          MRST/modules/ad-micp/

        # Install the current master version of DistMesh (for now to a version fixing a few warnings).
        git clone --branch dev --single-branch --depth 1 https://github.com/daavid00/DistMesh.git MRST/core/utils/3rdparty/DistMesh
        rm -rf MRST/core/utils/3rdparty/DistMesh/.git
      
    - name: Run the test
      run: |
        cd MRST/modules/ad-micp
        octave --no-gui --quiet tests/tests.m
