function paper = createPaperStruct(varargin)
    paper = struct('id', '',...
                   'name', '',...
                   'authors', '',...
                   'published', '',...
                   'url', '',...
                   'year', -1, ...
                   'modules', {{}}, ...
                   'fileurl', '');
    paper = merge_options(paper, varargin{:});
end