%% 1D Antiform Caprock with dissolution
% We consider a simple 1D antiform aquifer with a top surface given by the
% following expression
%      z = D - L1 * sin(x/L1)*tan(phi) + A sin(2*pi*x/L2)
% We study the case with and without subscale structure and with
% rate-dependent dissolution and without dissolution
           
runStandardModel('data/dissolutionExample1Data', @plotDissolutionFigs , ...
                 'depth', 1300                                        , ...
                 'residual', [false true]                             , ...
                 'A', [0 2]                                           , ...
                 'dis_types', {'none', 'rate'});             