%% Figure 1-3

% These figures are not generated by Matlab

%% Figure 4

% Left pane:
showAquiferModel;

% Right pane:
showDensityVariation;

%% Figure 5 and 6

residualExample;

%% Figure 7 and 8

clear all; firstPlioExample;

%% Figure 9

% This figure is not generated by Matlab

%% Figure 10
clear all; showUpscaledRelPerms;

%% Figure 11

% Left figure
clear all; close all;
upscalingExample;

% Right figure
showUpscaledRelPerms;

%% Figure 12, 13 and 14
clear all; close all;
dissolutionExample;

%% Figure 15

% This figure is not generated by Matlab


%% Figure 16

showSecondPlioExample();
