%% Figure 1-3

% These figures are not generated by Matlab

%% Figure 4

% Left pane:
showAquiferModel;

% Right pane:
showDensityVariation;

%% Figure 5 and 6

residualExample;

%% Figure 7
compare3D;


%% Figure 8 and 9

clear all; firstPlioExample;

%% Figure 11

% This figure is not generated by Matlab

%% Figure 12
clear all; showUpscaledRelPerms;

%% Figure 13

% Left figure
clear all; close all;
upscalingExample;

% Right figure
showUpscaledRelPerms;

%% Figure 14, 15 and 16
clear all; close all;
dissolutionExample;

%% Figure 17

% This figure is not generated by Matlab


%% Figure 18

showSecondPlioExample();
